### ISSUE TITLE
OC启动Win10蓝屏

### ISSUE THREAD

**Issue by 0ytian** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#1]
大佬从OC进win10会出现蓝屏吗？或者说bios要设置点什么？我之前用Clover没有这个问题

**Comment by Pinming** [comment]
我这里并不会啊…… 我也有见到 7590 机油有类似情况，考虑一下是不是 `Bitlocker` 没关？还讨论过 `AHCI / RAID` 和 `Secure Boot` 的可能，但都排除了。

**Comment by 0ytian** [comment]
问题找到了，我只关了win10的沙盒，没有关hyper-v，都关了之后就正常了

**Comment by Pinming** [comment]
> 问题找到了，我只关了win10的沙盒，没有关hyper-v，都关了之后就正常了

好的…… 感谢反馈了
