### ISSUE TITLE
睡眠唤醒黑屏

### ISSUE THREAD

**Issue by steven-panxd** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#11]
model: 7590 1080p
version: 10.15.4
按照步骤安装完成后其他功能都差不多正常就是睡眠不行 可以成功睡眠听到风扇挺转 但是唤醒之后会黑屏 但能看到屏幕背光是亮的并且用fn+F5/F6甚至能调节背光亮度 但就是黑屏 不知道为什么

**Comment by Pinming** [comment]
目前有发现类似问题。但是我自己用的 4K 没有发现 也不太清楚其他人解决了没有
我个人建议可以先替换一下 config 里的显卡 ID：
试一下 `3E9B0000` / `3E9B0009` / `3EA50009` 或者直接删去这项看一看吧……

**Comment by steven-panxd** [comment]
请问是指 `DeviceProperties > Add > AAPL,ig-platform-id` 的值么？

**Comment by steven-panxd** [comment]
感谢建议 但试过了并没有解决问题

**Comment by Pinming** [comment]
可以尝试更新到最新版的 `WhateverGreen` (`1.3.8`)，据机油说能解决问题。

**Comment by Pinming** [comment]
目前的 EFI 据 #12 反应已经解决该问题。

**Comment by steven-panxd** [comment]
他这个是背光不亮的情况 我的背光是量的
我做了一些测试 最后还是解决了 根据这个
https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/issues/43
我没有再测试你的EFI了 但我觉得应该都差不多吧
总而言之 谢谢你的回复

**Comment by ChasonJiang** [comment]
> 他这个是背光不亮的情况 我的背光是量的
> 
> 我做了一些测试 最后还是解决了 根据这个
> 
> https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/issues/43
> 
> 我没有再测试你的EFI了 但我觉得应该都差不多吧
> 
> 总而言之 谢谢你的回复



> 他这个是背光不亮的情况 我的背光是量的
> 
> 我做了一些测试 最后还是解决了 根据这个
> 
> https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/issues/43
> 
> 我没有再测试你的EFI了 但我觉得应该都差不多吧
> 
> 总而言之 谢谢你的回复

我和您的情况一样，但我看不太懂英文，可以麻烦您重新说下您是怎么解决的吗？

**Comment by steven-panxd** [comment]
把 `DeviceProperties > Add > PciRoot(0x0)/Pci(0x2,0x0)` 的值换成
`<dict> <key>AAPL,ig-platform-id</key> <data> AACbPg== </data> <key>disable-external-gpu</key> <data> AQAAAA== </data> <key>dpcd-max-link-rate</key> <data> CgAAAA== </data> <key>enable-dpcd-max-link-rate-fix</key> <data> AQAAAA== </data> <key>enable-hdmi-dividers-fix</key> <data> AQAAAA== </data> <key>enable-hdmi20</key> <data> AQAAAA== </data> <key>enable-lspcon-support</key> <data> AQAAAA== </data> <key>framebuffer-con1-alldata</key> <data> AQUJAAAEAACHAQAA </data> <key>framebuffer-con1-enable</key> <data> AQAAAA== </data> <key>framebuffer-con2-alldata</key> <data> AgYJAAAEAACHAQAA </data> <key>framebuffer-con2-enable</key> <data> AQAAAA== </data> <key>framebuffer-con3-alldata</key> <data> AwQKAAAIAACHAQAA </data> <key>framebuffer-con3-enable</key> <data> AQAAAA== </data> <key>framebuffer-con3-has-lspcon</key> <data> AQAAAA== </data> <key>framebuffer-patch-enable</key> <data> AQAAAA== </data> <key>framebuffer-portcount</key> <data> BAAAAA== </data> <key>framebuffer-unifiedmem</key> <data> AAAAgA== </data> </dict>`

**Comment by ChasonJiang** [comment]
> 在config.plist中把 `DeviceProperties > Add > PciRoot(0x0)/Pci(0x2,0x0)` 的值换成
> 
> `<dict> <key>AAPL,ig-platform-id</key> <data> AACbPg== </data> <key>disable-external-gpu</key> <data> AQAAAA== </data> <key>dpcd-max-link-rate</key> <data> CgAAAA== </data> <key>enable-dpcd-max-link-rate-fix</key> <data> AQAAAA== </data> <key>enable-hdmi-dividers-fix</key> <data> AQAAAA== </data> <key>enable-hdmi20</key> <data> AQAAAA== </data> <key>enable-lspcon-support</key> <data> AQAAAA== </data> <key>framebuffer-con1-alldata</key> <data> AQUJAAAEAACHAQAA </data> <key>framebuffer-con1-enable</key> <data> AQAAAA== </data> <key>framebuffer-con2-alldata</key> <data> AgYJAAAEAACHAQAA </data> <key>framebuffer-con2-enable</key> <data> AQAAAA== </data> <key>framebuffer-con3-alldata</key> <data> AwQKAAAIAACHAQAA </data> <key>framebuffer-con3-enable</key> <data> AQAAAA== </data> <key>framebuffer-con3-has-lspcon</key> <data> AQAAAA== </data> <key>framebuffer-patch-enable</key> <data> AQAAAA== </data> <key>framebuffer-portcount</key> <data> BAAAAA== </data> <key>framebuffer-unifiedmem</key> <data> AAAAgA== </data> </dict>`

可以了，非常感谢您的解答
