### ISSUE TITLE
IntelWiFi尝试

### ISSUE THREAD

**Issue by 0ytian** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#14]
有没有兴趣有空去尝试下驱动 [`IntelWiFI`](https://github.com/zxystd/itlwm)
我看这个repo是支持 `9560` 网卡的

**Comment by Pinming** [comment]
我已经测试过了，用是能用的，但是：
* 网速非常慢（＜200KB/s）
* 不支持系统原生的 Wifi 选择，SSID 和密码都写死在源码里面了
* 不能开机自启动

所以目前来讲可用性较低，暂时还不会考虑加入 EFI。

**Comment by 0ytian** [comment]
@Pinming 这倒是，不过可以关注下后续

**Comment by Pinming** [comment]
> @Pinming 这倒是，不过可以关注下后续

肯定会关注的，要是他搞成了那真是全人类感谢他了😂
