### ISSUE TITLE
大佬换了网卡吗

### ISSUE THREAD

**Issue by Odysseusq** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#17]
个人换了1820a，在win下信号差且蓝屏了一次就退了

**Comment by Pinming** [comment]
没开学 网卡在学校 所以依然换不了……
开学以后测试了也会更新最新的情况
据说 1820A 只有：
Part Number | Manufacturer | Module | WLAN | BT 4.1
-- | -- | -- | -- | --
CN-0VW3T3 | Dell Wireless 1820A 802.11ac | BCM94350ZAE_2 | 1028:0021 | [0a5c:6412]

这一款的情况略好一些……

**Comment by Odysseusq** [comment]
我是08PKF4，驱动还行但是win下表现真的辣鸡...
