### ISSUE TITLE
小问题合集

### ISSUE THREAD

**Issue by Odysseusq** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#18]
1.Combojack能识别耳机，但不识别耳麦；
2.键盘选项中关闭使用caps lock切换输入法的功能以后caps lock灯不亮了；
3.读条时会花一下屏（不知道是不是普遍这样）。

**Comment by Pinming** [comment]
1) 这个属于无解吧……据说好像只有部分 iPhone 原装耳机的麦克风可以识别，其他是不行的。
2) 这个不太清楚…… 应该属于系统设计的问题吧 我这边不太习惯用 Caps Lock 换输入法，平常还是 `Command + Space`。
3) 都会的，是正常现象。
