### ISSUE TITLE
耳麦问题

### ISSUE THREAD

**Issue by Klnsm** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#19]
安装了那个.sh文件重启后，有线耳机的麦克风还是无法使用，请问如何查看这个.sh的一件已经应用了

**Comment by Pinming** [comment]
除部分苹果原装耳机，其他耳机的麦克风均不能使用，这是正常现象。
像我的多条耳机甚至在 Windows 下面都没有麦克风功能…… 不奇怪
