### ISSUE TITLE
关于usb Wi-Fi

### ISSUE THREAD

**Issue by 0ytian** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#2]
大佬其实可以保留@tctien342的内置网卡驱动NullEthernet.kext，对于我这种经常在两个系统之间切换的人来说，DW1820A网卡并不稳定，反而USB WiFi更好使一点，但是如果不用NullEthernet.kext驱动，我在AppStore下载的App经常会出现账号问题

**Comment by Pinming** [comment]
好的……我考虑一下
1820a 真的不好用吗 我也在考虑到底换 1560 还是 1820

**Comment by 0ytian** [comment]
可能也看脸吧。。。我在tb上买的，就几十块钱。按照黑果小兵的方法屏蔽针脚之后win和mac都可以驱动，但是我偶尔还会玩一下游戏，就我感觉网络并不稳定，经常会跳ping，也可能是最近网络堵塞吧。至于DW1560，我在咸鱼淘了一块结果用不了，黑苹果都网卡水都挺深的，还是USB Wi-Fi先用着算了，有空再折腾看看～

**Comment by Pinming** [comment]
那感觉还尚可接受……我倒是有块 1820 在学校 但是现在不能开学也试不了……
