### ISSUE TITLE
求教大佬

### ISSUE THREAD

**Issue by XHL669** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#20]
emmm
本来不应该到这里问的，但还是希望大佬赐教
现在tctien342大佬发的更新都不是构建完的完整EFI包了，那想体验他的EFI该怎么操作呀？
英文渣渣，看他的redme没看出门道。。。
不知道您知不知道。。。

**Comment by Pinming** [comment]
他新版的我也没试过……不过我现在自己这套挺稳定的所以也暂时不大想测试他的版本了2333

**Comment by XHL669** [comment]
> 他新版的我也没试过……不过我现在自己这套挺稳定的所以也暂时不大想测试他的版本了2333

嗯，他不封装完整的包对小白很不友好。。。
行吧。
对了，最近Intel网卡上网有门道了，可以关注一下。
