### ISSUE TITLE
键盘灯无法控制关闭

### ISSUE THREAD

**Issue by kkwpsv** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#22]
通过键盘上控制键盘灯的fn+f5无法关闭，（据我观察，似乎）合盖之后，键盘灯也是亮的。

ps. 还遇到了一个小问题，我第一次用这个配置安装时，默认开了FileVault，第一次进系统正常，然后重启之后，就再也进不来，OpenCore选择完系统之后，就卡在白苹果。后面重新安装，不开启FileVault就一切正常，不知道是不是配置相关的问题？

**Comment by Pinming** [comment]
1) 键盘灯按理来说应该是 BIOS 在控制的把…… 我个人认为和黑苹果应该关系不大啊
2) 我目前也没有试过 FileVault…… 所以不太好回答这个问题 23333
至于具体配置可以参考一下黑果小兵的文章：https://blog.daliansky.net/OpenCore-BootLoader.html#%E5%9C%A8-opencore-%E4%B8%AD%E5%90%AF%E7%94%A8-filevault-%E6%96%87%E4%BB%B6%E4%BF%9D%E9%99%A9%E7%AE%B1

**Comment by kkwpsv** [comment]
好吧，filevalut问题不大，我选择直接关了。键盘灯竟然是归BIOS管了....记得好久之前用别的机型玩黑果，键盘灯要修dsdt来着，现在竟然不一样了。。我检查BIOS看看去......

**Comment by kkwpsv** [comment]
正常情况下是fn+f5控制键盘灯吧？我去bios转了一圈，没发现设置，然后顺便发现我windows键盘灯都控制不了了.........

**Comment by Pinming** [comment]
> 正常情况下是 fn+f5 控制键盘灯吧？我去 bios 转了一圈，没发现设置，然后顺便发现我 windows 键盘灯都控制不了了.........

会不会变成了单独按 F5 控制了…… 如果是这种情况可以按照我 readme 中相关内容修改一下

**Comment by kkwpsv** [comment]
> > 正常情况下是 fn+f5 控制键盘灯吧？我去 bios 转了一圈，没发现设置，然后顺便发现我 windows 键盘灯都控制不了了.........
> 
> 我出厂默认是单独按 F5 控制的…… 如果是这种情况可以按照我 readme 中 `升级 10.15.5 后可能发生 Fn 键设置改变` 相关内容修改一下
> 或者你直接按 `Fn + Esc` 应该也可以实现两种模式的切换

似乎我的键盘灯控制坏了`fn+f5`和`f5`都没用.....最近刚售后换了一次键盘，换完没试键盘灯。
