### ISSUE TITLE
【1820A / 随航正常】实装运行情况

### ISSUE THREAD

**Issue by Alice-space** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#23]
Dell 7591 1080p
网卡更换`DW1820A`
现在`airdrop`,`无线随航`,通过type-C连接的`有线随航`均工作正常
`HDMI`未使用
<img width="1424" alt="截屏2020-05-25 上午9 29 27" src="https://user-images.githubusercontent.com/47878052/82770202-3ddf7c80-9e6a-11ea-90ad-b294d68a1409.png">

**Comment by Pinming** [comment]
感谢测试！

**Comment by Pinming** [comment]
可以麻烦告知一下具体的型号吗，印象中只有 `BCM94350ZAE_2` 这一款 1820A 能够比较完美地运行。

**Comment by 0ytian** [comment]
@Pinming 3t3的dell版本不行吗😂

**Comment by Pinming** [comment]
> @Pinming 3t3的dell版本不行吗😂


表格来源：[黑果小兵](https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html)
Part Number | Manufacturer | Module | WLAN | BT 4.1
-- | -- | -- | -- | --
CN-0VW3T3 | Dell Wireless 1820A 802.11ac | BCM94350ZAE_2 | 1028:0021 | [0a5c:6412]
CN-0VW3T3 | Dell Wireless 1820A 802.11ac | BCM94356ZEPA50DX_2 | 1028:0021 | [0a5c:6412]

`3T3` 有两款的，听说只有 `ZAE_2` 效果比较好。

**Comment by Alice-space** [comment]
![21590665982_ pic_hd](https://user-images.githubusercontent.com/47878052/83137045-0c410c80-a11b-11ea-9472-69b6c91af160.jpg)
![11590665982_ pic_hd](https://user-images.githubusercontent.com/47878052/83137053-0fd49380-a11b-11ea-8e75-32b491e5b8ae.jpg)
为`BCM94356ZEPA50DX_2`,无需屏蔽针脚，只需要加载kext即可使用

**Comment by Pinming** [comment]
> ![21590665982_ pic_hd](https://user-images.githubusercontent.com/47878052/83137045-0c410c80-a11b-11ea-9472-69b6c91af160.jpg)
> ![11590665982_ pic_hd](https://user-images.githubusercontent.com/47878052/83137053-0fd49380-a11b-11ea-8e75-32b491e5b8ae.jpg)
> 为`BCM94356ZEPA50DX_2`,无需屏蔽针脚，只需要加载kext即可使用

 感谢！希望 ZAE_2 也能这么容易驱动（笑

**Comment by Pinming** [comment]
> > ![21590665982_ pic_hd](https://user-images.githubusercontent.com/47878052/83137045-0c410c80-a11b-11ea-9472-69b6c91af160.jpg)
> > ![11590665982_ pic_hd](https://user-images.githubusercontent.com/47878052/83137053-0fd49380-a11b-11ea-8e75-32b491e5b8ae.jpg)
> > 为`BCM94356ZEPA50DX_2`,无需屏蔽针脚，只需要加载kext即可使用
> 
> 感谢！希望 ZAE_2 也能这么容易驱动（笑

回到学校了……发现跟你这个是同款 那应该问题不大2333
