### ISSUE TITLE
升级Windows 10 2004之后，启动MacOS的问题

### ISSUE THREAD

**Issue by XHL669** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#26]
就是升级完Windows10 2004版本之后，从Windows关机，然后再按开机键进入MacOS读条会很慢
正常读条应该是两段，到中间左右突然变快。但是从Windows关机再切换到MacOS之后就是全程慢速读条。而且MacOS开机之后再关机也会很慢。
想要恢复正常需要长按电源键强制关机。
这是什么原因
我已经把Windows的快速启动关了，还是如此。
1908版本没有这样啊

**Comment by Pinming** [comment]
使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
这个暂时就没什么办法……

**Comment by XHL669** [comment]
> 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。

啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
那禁用蓝牙不可以吗？

**Comment by Pinming** [comment]
> > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> 
> 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> 那禁用蓝牙不可以吗？

那当然可以。
如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。

**Comment by XHL669** [comment]
> > > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> > 
> > 
> > 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> > 那禁用蓝牙不可以吗？
> 
> 那当然可以。
> 如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。
> 我这边如果从 Win 到 Mac 一般关机要等两三分钟再打开才不会卡蓝牙【捂脸】

在1908版本里也有过这个问题，然后我在电源选项里把快速启动关掉了就好了。
2004版关了也不管用。。。
想让笔记本冷启动只有长按电源强制关机的方法吗？
还有宁换的网卡有链接吗。。。

**Comment by XHL669** [comment]
> > > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> > 
> > 
> > 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> > 那禁用蓝牙不可以吗？
> 
> 那当然可以。
> 如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。
> 我这边如果从 Win 到 Mac 一般关机要等两三分钟再打开才不会卡蓝牙【捂脸】

在1908版本里也有过这个问题，然后在电源选项里把快速启动关掉了就好了。
2004版关了也不管用。。。

**Comment by XHL669** [comment]
> > > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> > 
> > 
> > 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> > 那禁用蓝牙不可以吗？
> 
> 那当然可以。
> 如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。
> 我这边如果从 Win 到 Mac 一般关机要等两三分钟再打开才不会卡蓝牙【捂脸】

让电脑冷启动只能长按电源键吗？
还有怎么屏蔽那个kext。。。

**Comment by Pinming** [comment]
> > > > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > > > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > > > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> > > 
> > > 
> > > 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> > > 那禁用蓝牙不可以吗？
> > 
> > 
> > 那当然可以。
> > 如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。
> > 我这边如果从 Win 到 Mac 一般关机要等两三分钟再打开才不会卡蓝牙【捂脸】
> 
> 让电脑冷启动只能长按电源键吗？
> 还有怎么屏蔽那个kext。。。
冷启动一般来说正常关机一两分钟或者三五分钟就算冷启动了吧……这个得自己把握。
长按关机完很快就开机的话，我这边试过也可能会卡进度条的。
屏蔽 kext，在 OC Configurator -> `Kernel` -> `Add` 中把对应 kext 的 Enabled 一栏的勾去掉就好。
![image](https://user-images.githubusercontent.com/30550234/83328762-13515180-a2b8-11ea-9b3b-4ab34184a2d4.png)

**Comment by XHL669** [comment]
> > > > > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > > > > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > > > > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> > > > 
> > > > 
> > > > 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> > > > 那禁用蓝牙不可以吗？
> > > 
> > > 
> > > 那当然可以。
> > > 如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。
> > > 我这边如果从 Win 到 Mac 一般关机要等两三分钟再打开才不会卡蓝牙【捂脸】
> > 
> > 
> > 让电脑冷启动只能长按电源键吗？
> > 还有怎么屏蔽那个kext。。。
> 
> 冷启动一般来说正常关机一两分钟或者三五分钟就算冷启动了吧……这个得自己把握。
> 长按关机完很快就开机的话，我这边试过也可能会卡进度条的。
> 屏蔽 kext，在 OC Configurator -> `Kernel` -> `Add` 中把对应 kext 的 Enabled 一栏的勾去掉就好。

额，怎么调整OC的启动顺序，，，Windows升级的时候第一启动项变成Windows了
而且宁的DW1820A在哪什么价位入的

**Comment by Pinming** [comment]
> > > > > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > > > > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > > > > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> > > > 
> > > > 
> > > > 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> > > > 那禁用蓝牙不可以吗？
> > > 
> > > 
> > > 那当然可以。
> > > 如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。
> > > 我这边如果从 Win 到 Mac 一般关机要等两三分钟再打开才不会卡蓝牙【捂脸】
> > 
> > 
> > 让电脑冷启动只能长按电源键吗？
> > 还有怎么屏蔽那个kext。。。
> 
> 冷启动一般来说正常关机一两分钟或者三五分钟就算冷启动了吧……这个得自己把握。
> 长按关机完很快就开机的话，我这边试过也可能会卡进度条的。
> 屏蔽 kext，在 OC Configurator -> `Kernel` -> `Add` 中把对应 kext 的 Enabled 一栏的勾去掉就好。



> > > > > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > > > > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > > > > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> > > > 
> > > > 
> > > > 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> > > > 那禁用蓝牙不可以吗？
> > > 
> > > 
> > > 那当然可以。
> > > 如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。
> > > 我这边如果从 Win 到 Mac 一般关机要等两三分钟再打开才不会卡蓝牙【捂脸】
> > 
> > 
> > 让电脑冷启动只能长按电源键吗？
> > 还有怎么屏蔽那个kext。。。
> 
> 冷启动一般来说正常关机一两分钟或者三五分钟就算冷启动了吧……这个得自己把握。
> 长按关机完很快就开机的话，我这边试过也可能会卡进度条的。
> 屏蔽 kext，在 OC Configurator -> `Kernel` -> `Add` 中把对应 kext 的 Enabled 一栏的勾去掉就好。

你指的是 BIOS 引导顺序嘛……那个不是 BIOS 里面设置就好了么
OC 的话我没调过，建议参考一下官方文档。
我去年暑假入的，才 70 多，现在肯定涨了（理财产品

**Comment by XHL669** [comment]
> > > > > > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > > > > > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > > > > > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> > > > > 
> > > > > 
> > > > > 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> > > > > 那禁用蓝牙不可以吗？
> > > > 
> > > > 
> > > > 那当然可以。
> > > > 如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。
> > > > 我这边如果从 Win 到 Mac 一般关机要等两三分钟再打开才不会卡蓝牙【捂脸】
> > > 
> > > 
> > > 让电脑冷启动只能长按电源键吗？
> > > 还有怎么屏蔽那个kext。。。
> > 
> > 
> > 冷启动一般来说正常关机一两分钟或者三五分钟就算冷启动了吧……这个得自己把握。
> > 长按关机完很快就开机的话，我这边试过也可能会卡进度条的。
> > 屏蔽 kext，在 OC Configurator -> `Kernel` -> `Add` 中把对应 kext 的 Enabled 一栏的勾去掉就好。
> 
> > > > > > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > > > > > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > > > > > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> > > > > 
> > > > > 
> > > > > 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> > > > > 那禁用蓝牙不可以吗？
> > > > 
> > > > 
> > > > 那当然可以。
> > > > 如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。
> > > > 我这边如果从 Win 到 Mac 一般关机要等两三分钟再打开才不会卡蓝牙【捂脸】
> > > 
> > > 
> > > 让电脑冷启动只能长按电源键吗？
> > > 还有怎么屏蔽那个kext。。。
> > 
> > 
> > 冷启动一般来说正常关机一两分钟或者三五分钟就算冷启动了吧……这个得自己把握。
> > 长按关机完很快就开机的话，我这边试过也可能会卡进度条的。
> > 屏蔽 kext，在 OC Configurator -> `Kernel` -> `Add` 中把对应 kext 的 Enabled 一栏的勾去掉就好。
> 
> 你指的是 BIOS 引导顺序嘛……那个不是 BIOS 里面设置就好了么
> OC 的话我没调过，建议参考一下官方文档。
> 我去年暑假入的，才 70 多，现在肯定涨了（理财产品

可以，确实涨了，90最低，有的卖160.。。。
最后建议宁搞两个分支，intel版本和DW分开，方便没有换网卡的测试以后的版本。。。

**Comment by Pinming** [comment]
> > > > > > > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > > > > > > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > > > > > > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> > > > > > 
> > > > > > 
> > > > > > 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> > > > > > 那禁用蓝牙不可以吗？
> > > > > 
> > > > > 
> > > > > 那当然可以。
> > > > > 如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。
> > > > > 我这边如果从 Win 到 Mac 一般关机要等两三分钟再打开才不会卡蓝牙【捂脸】
> > > > 
> > > > 
> > > > 让电脑冷启动只能长按电源键吗？
> > > > 还有怎么屏蔽那个kext。。。
> > > 
> > > 
> > > 冷启动一般来说正常关机一两分钟或者三五分钟就算冷启动了吧……这个得自己把握。
> > > 长按关机完很快就开机的话，我这边试过也可能会卡进度条的。
> > > 屏蔽 kext，在 OC Configurator -> `Kernel` -> `Add` 中把对应 kext 的 Enabled 一栏的勾去掉就好。
> > 
> > 
> > > > > > > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > > > > > > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > > > > > > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> > > > > > 
> > > > > > 
> > > > > > 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> > > > > > 那禁用蓝牙不可以吗？
> > > > > 
> > > > > 
> > > > > 那当然可以。
> > > > > 如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。
> > > > > 我这边如果从 Win 到 Mac 一般关机要等两三分钟再打开才不会卡蓝牙【捂脸】
> > > > 
> > > > 
> > > > 让电脑冷启动只能长按电源键吗？
> > > > 还有怎么屏蔽那个kext。。。
> > > 
> > > 
> > > 冷启动一般来说正常关机一两分钟或者三五分钟就算冷启动了吧……这个得自己把握。
> > > 长按关机完很快就开机的话，我这边试过也可能会卡进度条的。
> > > 屏蔽 kext，在 OC Configurator -> `Kernel` -> `Add` 中把对应 kext 的 Enabled 一栏的勾去掉就好。
> > 
> > 
> > 你指的是 BIOS 引导顺序嘛……那个不是 BIOS 里面设置就好了么
> > OC 的话我没调过，建议参考一下官方文档。
> > 我去年暑假入的，才 70 多，现在肯定涨了（理财产品
> 
> 可以，确实涨了，90最低，有的卖160.。。。
> 最后建议宁搞两个分支，intel版本和DW分开，方便没有换网卡的测试以后的版本。。。

有点懒 233333 我考虑弄下吧 最近期末了有点忙（逃

**Comment by XHL669** [comment]
> > > > > > > > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > > > > > > > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > > > > > > > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> > > > > > > 
> > > > > > > 
> > > > > > > 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> > > > > > > 那禁用蓝牙不可以吗？
> > > > > > 
> > > > > > 
> > > > > > 那当然可以。
> > > > > > 如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。
> > > > > > 我这边如果从 Win 到 Mac 一般关机要等两三分钟再打开才不会卡蓝牙【捂脸】
> > > > > 
> > > > > 
> > > > > 让电脑冷启动只能长按电源键吗？
> > > > > 还有怎么屏蔽那个kext。。。
> > > > 
> > > > 
> > > > 冷启动一般来说正常关机一两分钟或者三五分钟就算冷启动了吧……这个得自己把握。
> > > > 长按关机完很快就开机的话，我这边试过也可能会卡进度条的。
> > > > 屏蔽 kext，在 OC Configurator -> `Kernel` -> `Add` 中把对应 kext 的 Enabled 一栏的勾去掉就好。
> > > 
> > > 
> > > > > > > > 使用的是英特尔的网卡吗……应该是蓝牙固件的问题。
> > > > > > > > 2004 版本自带蓝牙新固件了，回滚也没用貌似。旧版 1909 的系统可以回滚到老版本固件。
> > > > > > > > 这个暂时就没什么办法……建议就只能冷启动 Mac 系统会好一些。
> > > > > > > 
> > > > > > > 
> > > > > > > 啊这，这是什么原理。。。都已经把快速启动关掉了，不是冷启动吗？
> > > > > > > 那禁用蓝牙不可以吗？
> > > > > > 
> > > > > > 
> > > > > > 那当然可以。
> > > > > > 如果你不是很需要蓝牙可以直接在 OC 里屏蔽 `IntelBluetooth` 开头的 kext，应该能避免这个问题。
> > > > > > 我这边如果从 Win 到 Mac 一般关机要等两三分钟再打开才不会卡蓝牙【捂脸】
> > > > > 
> > > > > 
> > > > > 让电脑冷启动只能长按电源键吗？
> > > > > 还有怎么屏蔽那个kext。。。
> > > > 
> > > > 
> > > > 冷启动一般来说正常关机一两分钟或者三五分钟就算冷启动了吧……这个得自己把握。
> > > > 长按关机完很快就开机的话，我这边试过也可能会卡进度条的。
> > > > 屏蔽 kext，在 OC Configurator -> `Kernel` -> `Add` 中把对应 kext 的 Enabled 一栏的勾去掉就好。
> > > 
> > > 
> > > 你指的是 BIOS 引导顺序嘛……那个不是 BIOS 里面设置就好了么
> > > OC 的话我没调过，建议参考一下官方文档。
> > > 我去年暑假入的，才 70 多，现在肯定涨了（理财产品
> > 
> > 
> > 可以，确实涨了，90最低，有的卖160.。。。
> > 最后建议宁搞两个分支，intel版本和DW分开，方便没有换网卡的测试以后的版本。。。
> 
> 有点懒 233333 我考虑弄下吧 最近期末了有点忙（逃

好的，感谢
（我们学校这学期不开了，等8月再考试（嘻嘻

**Comment by XHL669** [comment]
是我打开方式不对吗，为什么OCC里面所有选项都是空白的。。。
![截屏2020-05-30 下午11 10 31](https://user-images.githubusercontent.com/63577165/83331997-65e83900-a2cb-11ea-9273-cb256be5640f.png)

**Comment by Pinming** [comment]
> 是我打开方式不对吗，为什么OCC里面所有选项都是空白的。。。
> ![截屏2020-05-30 下午11 10 31](https://user-images.githubusercontent.com/63577165/83331997-65e83900-a2cb-11ea-9273-cb256be5640f.png)

你要自己打开 EFI 分区里的 config.plist 啊 23333

**Comment by XHL669** [comment]
> > 是我打开方式不对吗，为什么OCC里面所有选项都是空白的。。。
> > ![截屏2020-05-30 下午11 10 31](https://user-images.githubusercontent.com/63577165/83331997-65e83900-a2cb-11ea-9273-cb256be5640f.png)
> 
> 你要自己打开 EFI 分区里的 config.plist 啊 23333

好了。。。
