### ISSUE TITLE
200530版本，如何开启intel的蓝牙

### ISSUE THREAD

**Issue by casper-kang** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#27]
RT，小白求教

**Comment by Pinming** [comment]
已经开了一个 `IntelBT` 的分支了，那个就跟之前的设置一样了。
如果想在 master 分支上自己修改，请参照以前版本的 readme，在 OCC 中勾选启用 `IntelBluetooth***.kext`，同时关闭与博通网卡相关的 kext 就好了。
`master` 和 `IntelBT` 除此以外别无二致。

**Comment by casper-kang** [comment]
十分感谢
