### ISSUE TITLE
明显感觉耗电好快，用不到两个小时就差不多没电了，有解决方案嘛？

### ISSUE THREAD

**Issue by Kro-xu** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#28]

**Comment by Pinming** [comment]
请问下使用的电池是 56Wh 的还是 97Wh 的呢……
我这边 97Wh 的话，上上网码代码啥的一般能有 5h 左右啊

**Comment by Kro-xu** [comment]
不晓得，这个在哪看哦🤣，你的这么强5h？

**Comment by Pinming** [comment]
> 不晓得，这个在哪看哦🤣，你的这么强5h？

这个买机器的时候不就应该知道电池容量了嘛😄有 SATA 盘位的就 56Wh，没有的就 97Wh 啊。

**Comment by Kro-xu** [comment]
看了下，好像是56，但是在win或者Linux就可以用到四个小时左右

**Comment by Pinming** [comment]
多少是会比 Windows 少一些的…… 后期我也会再试试能不能优化一下，不过应该也不会有很明显的效果了 2333
