### ISSUE TITLE
Pls help 

### ISSUE THREAD

**Issue by marcinkk** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#29]
Hey, how do you set the keys to adjust the screen brightness on a laptop keyboard ?? Right now it's fn + f12 and fn + key pause. My bootloader is opencore. In my laptop acer v3-371, the shortcut from adjusting the screen brightness on the keyboard is the shortcut fn + left arrow key and fn + arrow right key.

**Comment by Pinming** [comment]
You can reference: https://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/
and patch DSDT to remap the keys by yourself.
