### ISSUE TITLE
新版efi导致hdmi闪屏

### ISSUE THREAD

**Issue by babuf** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#3]
我是i5的，1080p屏幕，不知道为什么用了最新推的efi之后连hdmi的屏幕会狂闪。。。。

**Comment by babuf** [comment]
好吧，我发现了，我就是那个hdmi bug 上一个版本貌似没这个问题的。。。。这次我用新的efi重装就出现了

**Comment by Pinming** [comment]
你是 telegram 上那位吗😂
