### ISSUE TITLE
开机时【偶尔】卡在苹果logo处很久才能进入系统、进入系统或休眠唤醒后【经常】黑屏，需要强制重启

### ISSUE THREAD

**Issue by zhuziqi0010** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#30]
大佬好，我的7590除了没有升级内存和你的配置一模一样，直接使用的你的efi，只修改了三码。用的是10.15.5系统
问题是：开机时偶尔卡在苹果logo处很久才能进入系统、进入系统或休眠唤醒后经常黑屏

我怀疑开机卡logo是intel 9560ac蓝牙的问题，因为卡logo启动后往往不识别蓝牙
希望大佬能帮我分析一下黑屏的问题，谢谢啦

最后感谢大佬让我一个穷学生用上了苹果电脑（雾）
如果能解决了黑屏问题，基本上就可以日用了

**Comment by Pinming** [comment]
感谢测试。麻烦说明一下版本 （4K / 1080P）。
1) 卡 Logo 一般就是英特尔蓝牙问题，这个除了回退蓝牙固件应该没有什么其他办法。<br>我个人测试的话，如果 Win10 升级到了 2004 版本就很难回退到初始固件了，哪怕手动回退应该也会自动更新回去。
2) 黑屏的话我想大概率应该是你是 1080P 机型的。可以考虑一下改 `config.plist` 中的显卡 ID（即 `AAPL,ig-platform-id` 的键值）。<br>可以尝试一下`留空`、`0900A53E`、`00009B3E` 这几个。

**Comment by Pinming** [comment]
> 感谢测试。麻烦说明一下版本 （4K / 1080P）。
> 
> 1. 卡 Logo 一般就是英特尔蓝牙问题，这个除了回退蓝牙固件应该没有什么其他办法。我个人测试的话，如果 Win10 升级到了 2004 版本就很难回退到初始固件了，哪怕手动回退应该也会自动更新回去。
> 2. 黑屏的话我想大概率应该是你是 1080P 机型的。可以考虑一下改 `config.plist` 中的显卡 ID（即 `AAPL,ig-platform-id` 的键值）。可以尝试一下`留空`、`0900A53E`、`00009B3E` 这几个。

噢是 4K 的啊…… 那我觉得还是有点奇怪的。你是友达屏还是夏普屏呢……
4K 默认设置是留空 ID，你可以尝试填入上面的两个 ID 看看。
如果仍然不行可以考虑删除 `igfwfw=2` 参数再试试。
再不行的话，就更换旧版的 `WhateverGreen` 试试吧，但需要 ≥`1.3.7`。

**Comment by zhuziqi0010** [comment]
> > 感谢测试。麻烦说明一下版本 （4K / 1080P）。
> > 
> > 1. 卡 Logo 一般就是英特尔蓝牙问题，这个除了回退蓝牙固件应该没有什么其他办法。我个人测试的话，如果 Win10 升级到了 2004 版本就很难回退到初始固件了，哪怕手动回退应该也会自动更新回去。
> > 2. 黑屏的话我想大概率应该是你是 1080P 机型的。可以考虑一下改 `config.plist` 中的显卡 ID（即 `AAPL,ig-platform-id` 的键值）。可以尝试一下`留空`、`0900A53E`、`00009B3E` 这几个。
> 
> 噢是 4K 的啊…… 那我觉得还是有点奇怪的。你是友达屏还是夏普屏呢……
> 4K 默认设置是留空 ID，你可以尝试填入上面的两个 ID 看看。
> 如果仍然不行可以考虑删除 `igfxfw=2` 参数再试试。
> 再不行的话，就更换旧版的 `WhateverGreen` 试试吧，但需要 ≥`1.3.7`。



没错，是4k屏，夏普14C7
最近考试比较多，我稍后再试一下再来汇报情况(ฅ´ω`ฅ)

**Comment by zhuziqi0010** [comment]
我来报告了：
前几天把 Windows 折腾坏了，重新装了 LTSC2019
并且重新下载了原版 efi
蓝牙目前可用了，开机速度杠杠的
偶尔会出现开机黑屏的情况（我冷启动热启动试了好多次，只出现了一次）
盒盖休眠后再打开就可以正常亮屏了（玄学问题）

再次感谢大佬愿意花时间指导问题！
