### ISSUE TITLE
关于双系统opencore进win10卡住的问题

### ISSUE THREAD

**Issue by zhaogarvie** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#32]
问题如标题，在oc选择win10后会进入系统转一会儿圈，然后开始卡死，同时圈圈转不动，并且系统风扇开始高速转动。只能通过强制关机来关机。
不知作者可否给一点见解。
在efi中我也放入了原来clover引导时的microsoft文件夹。

**Comment by Pinming** [comment]
啊这…… 我没见过这个问题啊 23333，这个我也不清楚咋办了【捂脸】

**Comment by zhaogarvie** [comment]
> 啊这…… 我没见过这个问题啊 23333，这个我也不清楚咋办了【捂脸】

那请问你是完全畅通无阻的就进入了win系统吗？😂

**Comment by Pinming** [comment]
> > 啊这…… 我没见过这个问题啊 23333，这个我也不清楚咋办了【捂脸】
> 
> 那请问你是完全畅通无阻的就进入了 win 系统吗？😂

我这边基本没啥问题 23333

**Comment by Pinming** [comment]
我这边 EFI 的结构：
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          8/2/2019   1:44 PM                APPLE
d-----         2/11/2020   7:32 AM                Boot
d-----          5/6/2020   5:27 PM                OC
d-----         7/20/2019   5:16 PM                Microsoft
da----         5/22/2020   5:16 AM                dell
-a----         4/10/2020   5:24 PM          83072 HiiDatabase.efi
-a----         4/10/2020   5:24 PM         136512 OpenCanopy.efi
-a----         1/17/2019   4:27 AM           8196 .DS_Store
```

这边 Microsoft 文件夹的结构：
```
PS C:\WINDOWS\system32> tree y:\efi\microsoft
Folder PATH listing for volume ESP
Volume serial number is 8EDA-C23A
Y:\EFI\MICROSOFT
├───Boot
│   ├───bg-BG
│   ├───cs-CZ
│   ├───da-DK
│   ├───de-DE
│   ├───el-GR
│   ├───en-GB
│   ├───en-US
│   ├───es-ES
│   ├───es-MX
│   ├───et-EE
│   ├───fi-FI
│   ├───Fonts
│   ├───fr-CA
│   ├───fr-FR
│   ├───hr-HR
│   ├───hu-HU
│   ├───it-IT
│   ├───ja-JP
│   ├───ko-KR
│   ├───lt-LT
│   ├───lv-LV
│   ├───nb-NO
│   ├───nl-NL
│   ├───pl-PL
│   ├───pt-BR
│   ├───pt-PT
│   ├───qps-ploc
│   ├───Resources
│   │   ├───en-US
│   │   ├───ja-JP
│   │   └───zh-CN
│   ├───ro-RO
│   ├───ru-RU
│   ├───sk-SK
│   ├───sl-SI
│   ├───sr-Latn-RS
│   ├───sv-SE
│   ├───tr-TR
│   ├───uk-UA
│   ├───zh-CN
│   └───zh-TW
└───Recovery
```

**Comment by Pinming** [comment]
> > 啊这…… 我没见过这个问题啊 23333，这个我也不清楚咋办了【捂脸】
> 
> 那请问你是完全畅通无阻的就进入了 win 系统吗？😂

我盲猜会不会是 `RAID / AHCI` 模式的问题啊…… 一般来讲选 `AHCI` 会好操作一些。
不过这个一般会导致蓝屏而不是卡死。就只是个猜测 23333

**Comment by zhaogarvie** [comment]
> > > 啊这…… 我没见过这个问题啊 23333，这个我也不清楚咋办了【捂脸】
> > 
> > 
> > 那请问你是完全畅通无阻的就进入了 win 系统吗？😂
> 
> 我盲猜会不会是 `RAID / AHCI` 模式的问题啊…… 一般来讲选 `AHCI` 会好操作一些。
> 不过这个一般会导致蓝屏而不是卡死。就只是个猜测 23333

我本来就是ahci模式了，因为之前用clover的时候就raid进不去，只能换成ahci才能进mac，所以一直用的ahci。早上试了一下这个问题还是没法解决。

另外我想问一下您就是您电脑开机进opencore也是会出现个十几二十秒的代码的吗？我每次开机都需要屏幕滚动十几二十秒的代码才进入opencore，然后再选择系统又加载好一会儿，整体的开机时间都超过我以前用clover的开机时间了，请问您有什么看法吗

**Comment by Pinming** [comment]
> > > > 啊这…… 我没见过这个问题啊 23333，这个我也不清楚咋办了【捂脸】
> > > 
> > > 
> > > 那请问你是完全畅通无阻的就进入了 win 系统吗？joy
> > 
> > 
> > 我盲猜会不会是 `RAID / AHCI` 模式的问题啊…… 一般来讲选 `AHCI` 会好操作一些。
> > 不过这个一般会导致蓝屏而不是卡死。就只是个猜测 23333
> 
> 我本来就是ahci模式了，因为之前用clover的时候就raid进不去，只能换成ahci才能进mac，所以一直用的ahci。早上试了一下这个问题还是没法解决。
> 
> 另外我想问一下您就是您电脑开机进opencore也是会出现个十几二十秒的代码的吗？我每次开机都需要屏幕滚动十几二十秒的代码才进入opencore，然后再选择系统又加载好一会儿，整体的开机时间都超过我以前用clover的开机时间了，请问您有什么看法吗

Opencore 加载前滚代码？那样一般也会卡住进不去的啊（因为 config.plist 有不符合当前 OC 版本的键值）。
麻烦贴一份滚代码的画面看看内容吧…… 不然不是很好判断。
另外方便的话请附上当前配置的 `config.plist`，谢谢！

**Comment by zhaogarvie** [comment]
下面是我上传在公用图床的6张图片，按顺序是从刚开机到进入oc选择界面，这个过程需要1分15秒。
然后我再选择mac进系统，整个开机就花了两分钟了😂
https://imgchr.com/i/t4YoqA
https://imgchr.com/i/t4YRPK
https://imgchr.com/i/t4Yf2D
https://imgchr.com/i/t4YcUx
https://imgchr.com/i/t4Yg56
https://imgchr.com/i/t4YW8O

我当前的config.plist就是直接用的你上传的1080p版本的那个config，没有修改
另外我是基本上直接用了你的EFI。唯一的修改是我把你的/EFI/Drivers/OpenRuntime.efi换成了官方版本的。因为不更换的话我加载oc滚代码会卡在如下地方
OCABC: Incompatible OpenRuntime r10, required r11
Halting on critical error

**Comment by Pinming** [comment]
这我是真不知道了【捂脸】 我还真没碰到过这种问题 求助一下其他巨佬吧 233333

**Comment by zhaogarvie** [comment]
> 这我是真不知道了【捂脸】 我还真没碰到过这种问题 求助一下其他巨佬吧 233333

你好，我自己发现问题解决方法了。因为你给的EFI对应的OpenCore是4月10日版本的，我直接从github上下的是最新版的，所以我们的oc版本不一样，这样的话就算我用了你的efi还是会有代码什么什么的，现在我把我的oc换成了4月10日版本的，就没有这些滚代码什么的问题了，也能正常进入windows了。
问题完美解决，谢谢！
