### ISSUE TITLE
【耳机耳麦】有个小建议大佬你要尝试一下吗？

### ISSUE THREAD

**Issue by zhaogarvie** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#35]
你好，就是我发现我用了你的EFI之后就算装了ComboJack，插入耳机也只能听声音没法用耳麦。而在我换到你的OpenCore之前我用的是CLOVER，我那个CLOVER的话，开机插耳机有几率全是电流声没法用，也有50%是插上耳机是可以使用耳麦的，大佬你有兴趣研究一下吗？我当初的那个CLOVER我还保留着，如果你感兴趣的话我可以分享给你。我当初的那个能用耳麦的版本的话，插入耳机是会弹出选择界面的。

**Comment by seepine** [comment]
同时你也可以到[tctien342](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh)这位大佬项目中发issue，让两位大佬一起解决麦克风问题，解决后灵越759x系列黑果基本完美了

**Comment by Pinming** [comment]
> 你好，就是我发现我用了你的EFI之后就算装了ComboJack，插入耳机也只能听声音没法用耳麦。而在我换到你的OpenCore之前我用的是CLOVER，我那个CLOVER的话，开机插耳机有几率全是电流声没法用，也有50%是插上耳机是可以使用耳麦的，大佬你有兴趣研究一下吗？我当初的那个CLOVER我还保留着，如果你感兴趣的话我可以分享给你。我当初的那个能用耳麦的版本的话，插入耳机是会弹出选择界面的。

可以发份过来我参考一下😂不过我现在很快期末考试了 近期应该没有什么时间处理这些 2333 当然能力范围内我也尽量提供帮助吧
至于 ComboJack 本身就是 t 大 `tctien342` 做出来的，直接联系他的话应该效率更高思路也更清晰~

**Comment by zhaogarvie** [comment]
没事大佬反正这CLOVER我也没法用了， 毕竟整体体验上还是你的OC更舒服，我直接上传到我Github了，你有空感兴趣的话可以去看看🤣
[https://github.com/zhaogarvie/Dell-Inspiron-7591-CLOVER-Hackintosh](url)

**Comment by Pinming** [comment]
> 没事大佬反正这 CLOVER 我也没法用了， 毕竟整体体验上还是你的 OC 更舒服，我直接上传到我 Github 了，你有空感兴趣的话可以去看看🤣
> [https://github.com/zhaogarvie/Dell-Inspiron-7591-CLOVER-Hackintosh](url)

好的，谢谢了
