### ISSUE TITLE
OC引导中出现lilu user @ failed to change memory protection (0，2)

### ISSUE THREAD

**Issue by illusion899** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#36]
大佬，请教OC安装系统时显示lilu user @ failed to change memory protection (0 2)，并在后面导致memory panic stackshot succeeded ** bytes traced XXXXX**. 最后安装或者启动无法继续。

用的是您的这个oc的efi文档里的全部内容，机器配置是

SKU | [XPS-7590]
CPU | Intel Core i7 9750H
GPU | Intel Graphics UHD 630
Built-In Screen | 1080 FHD
RAM |  32GB (2 x 16GB) DDR4  2666MHz
Audio | Realtek ALC298
Wireless | Dell Wireless DW1820A
 
卡在这个问题及已经两天了，求指导
![IMG_20200611_190249](https://user-images.githubusercontent.com/66808454/84453830-6ef1e680-ac8b-11ea-958f-d0a1dfc55d4f.jpg)

**Comment by Pinming** [comment]
这个 -v 图我不太看得出问题…… 这是最后一刻的 -v 图画面吗？-v 图走完以后是卡住、黑屏还是直接重启呢？
然后如果是 XPS 的话 我还是建议使用 XPS 机型的 EFI 吧😂 毕竟两个机器在 ACPI 表上还是有一些差别的

**Comment by illusion899** [comment]
最后一刻是卡住，会在屏幕上显示memory panic stackshot succeeded ** bytes traced XXXXX**，风扇疯狂旋转但是没有再向下，原来以为是bios的问题，原来是1.6.0,现在降级到1.4.0还是一样，换了lilu到最新版还是这个问题。我看您这个帖子就是759x系列的呀，还有您说的这个简化驱动是指简化到什么程度呢？谢谢

**Comment by Pinming** [comment]
> 最后一刻是卡住，会在屏幕上显示memory panic stackshot succeeded ** bytes traced XXXXX**，风扇疯狂旋转但是没有再向下，原来以为是bios的问题，原来是1.6.0,现在降级到1.4.0还是一样，换了lilu到最新版还是这个问题。您说的这个简化驱动是指简化到什么程度呢？谢谢

咱这里是 `灵越 759x` 的 efi 啊，不是 XPS 的😂所以我才说会有一定差别。
简化驱动就将集显/网卡等安装时不必要的驱动先屏蔽掉，比如集显就直接用 `0x12345678` 进系统看看；网卡就先直接关闭相关的 kext。因为你这个我也不太确定是哪里的问题，只能先这样猜测性尝试下了……

**Comment by illusion899** [comment]
刚刚意识到自己的愚蠢...好的大佬，我再试试，非常感谢~

**Comment by illusion899** [comment]
> > 最后一刻是卡住，会在屏幕上显示memory panic stackshot succeeded ** bytes traced XXXXX**，风扇疯狂旋转但是没有再向下，原来以为是bios的问题，原来是1.6.0,现在降级到1.4.0还是一样，换了lilu到最新版还是这个问题。您说的这个简化驱动是指简化到什么程度呢？谢谢
> 
> 咱这里是 `灵越 759x` 的 efi 啊，不是 XPS 的所以我才说会有一定差别。
> 简化驱动就将集显/网卡等安装时不必要的驱动先屏蔽掉，比如集显就直接用 `0x12345678` 进系统看看；网卡就先直接关闭相关的 kext。因为你这个我也不太确定是哪里的问题，只能先这样猜测性尝试下了……

大佬，在帮助下找到了合适的efi，非常感谢，还有一个问题想请教一下，我用0.5.9的opencore引导的时候第一项是叫No Name， 下面才是win和mac，请问能删除这个选项吗？

**Comment by Pinming** [comment]
> > > 最后一刻是卡住，会在屏幕上显示 memory panic stackshot succeeded ** bytes traced XXXXX**，风扇疯狂旋转但是没有再向下，原来以为是 bios 的问题，原来是 1.6.0, 现在降级到 1.4.0 还是一样，换了 lilu 到最新版还是这个问题。您说的这个简化驱动是指简化到什么程度呢？谢谢
> > 
> > 
> > 咱这里是 `灵越 759x` 的 efi 啊，不是 XPS 的所以我才说会有一定差别。
> > 简化驱动就将集显 / 网卡等安装时不必要的驱动先屏蔽掉，比如集显就直接用 `0x12345678` 进系统看看；网卡就先直接关闭相关的 kext。因为你这个我也不太确定是哪里的问题，只能先这样猜测性尝试下了……
> 
> 大佬，在帮助下找到了合适的 efi，非常感谢，还有一个问题想请教一下，我用 0.5.9 的 opencore 引导的时候第一项是叫 No Name， 下面才是 win 和 mac，请问能删除这个选项吗？

No name 有没有可能是你插了带引导的 U 盘啥的…… Opencore 好像只能修改扫描磁盘的策略，而不能像 Clover 一样定向屏蔽某一盘符。
具体可以参考这篇文章的 `3.2` 部分：https://blog.xjn819.com/?p=543

**Comment by illusion899** [comment]
> > > > 最后一刻是卡住，会在屏幕上显示 memory panic stackshot succeeded ** bytes traced XXXXX**，风扇疯狂旋转但是没有再向下，原来以为是 bios 的问题，原来是 1.6.0, 现在降级到 1.4.0 还是一样，换了 lilu 到最新版还是这个问题。您说的这个简化驱动是指简化到什么程度呢？谢谢
> > > 
> > > 
> > > 咱这里是 `灵越 759x` 的 efi 啊，不是 XPS 的所以我才说会有一定差别。
> > > 简化驱动就将集显 / 网卡等安装时不必要的驱动先屏蔽掉，比如集显就直接用 `0x12345678` 进系统看看；网卡就先直接关闭相关的 kext。因为你这个我也不太确定是哪里的问题，只能先这样猜测性尝试下了……
> > 
> > 
> > 大佬，在帮助下找到了合适的 efi，非常感谢，还有一个问题想请教一下，我用 0.5.9 的 opencore 引导的时候第一项是叫 No Name， 下面才是 win 和 mac，请问能删除这个选项吗？
> 
> No name 有没有可能是你插了带引导的 U 盘啥的…… Opencore 好像只能修改扫描磁盘的策略，而不能像 Clover 一样定向屏蔽某一盘符。
> 具体可以参考这篇文章的 `3.2` 部分：https://blog.xjn819.com/?p=543

谢谢大佬，我研究一下。再问几个愚蠢的问题，在10.15.5之后的这些版本，hackintools和opencore 的主程序如何更新呢？kext的更新只能用命令行吗？一般用什么在mac下面编辑plist比较好呢？感谢感谢！

**Comment by Pinming** [comment]
> > > > > 最后一刻是卡住，会在屏幕上显示 memory panic stackshot succeeded ** bytes traced XXXXX**，风扇疯狂旋转但是没有再向下，原来以为是 bios 的问题，原来是 1.6.0, 现在降级到 1.4.0 还是一样，换了 lilu 到最新版还是这个问题。您说的这个简化驱动是指简化到什么程度呢？谢谢
> > > > 
> > > > 
> > > > 咱这里是 `灵越 759x` 的 efi 啊，不是 XPS 的所以我才说会有一定差别。
> > > > 简化驱动就将集显 / 网卡等安装时不必要的驱动先屏蔽掉，比如集显就直接用 `0x12345678` 进系统看看；网卡就先直接关闭相关的 kext。因为你这个我也不太确定是哪里的问题，只能先这样猜测性尝试下了……
> > > 
> > > 
> > > 大佬，在帮助下找到了合适的 efi，非常感谢，还有一个问题想请教一下，我用 0.5.9 的 opencore 引导的时候第一项是叫 No Name， 下面才是 win 和 mac，请问能删除这个选项吗？
> > 
> > 
> > No name 有没有可能是你插了带引导的 U 盘啥的…… Opencore 好像只能修改扫描磁盘的策略，而不能像 Clover 一样定向屏蔽某一盘符。
> > 具体可以参考这篇文章的 `3.2` 部分：https://blog.xjn819.com/?p=543
> 
> 谢谢大佬，我研究一下。再问几个愚蠢的问题，在 10.15.5 之后的这些版本，hackintools 和 opencore 的主程序如何更新呢？kext 的更新只能用命令行吗？一般用什么在 mac 下面编辑 plist 比较好呢？感谢感谢！

1) Hackintool 一般就正常更新就好了，这个没啥影响。
2) Opencore 在没有必要的情况下，我个人不太建议更新。因为目前的 OC 各版本间差异太大了，每次升级都要在 `config.plist` 上做很大的修改。所以如果能稳定使用了，且 OC 也没有什么重大改进了，我个人认为也就不太必要继续更新了。
3) kext 更新主要就是几个步骤：<br>- 复制进 `\EFI\OC (或 Clover)\Kexts` <br>- 在 OC 的 Config.plist 中添加并启用（Clover 就不需要了） <br> - 如果重启后不即时生效，Terminal 内清空缓存：`kextcache -i /`。
4) 如果你需要像 Clover 一样可视化地修改 config，可以在 https://mackie100projects.altervista.org/category/opencore-configurator-changelog/ 下载各版本的 `Opencore Configurator`，Changelog 里都会写支持的 OC 版本，注意对应就行了。或者你用 VSCode 啥的手动改也可以……

**Comment by illusion899** [comment]
> > > > > > 最后一刻是卡住，会在屏幕上显示 memory panic stackshot succeeded ** bytes traced XXXXX**，风扇疯狂旋转但是没有再向下，原来以为是 bios 的问题，原来是 1.6.0, 现在降级到 1.4.0 还是一样，换了 lilu 到最新版还是这个问题。您说的这个简化驱动是指简化到什么程度呢？谢谢
> > > > > 
> > > > > 
> > > > > 咱这里是 `灵越 759x` 的 efi 啊，不是 XPS 的所以我才说会有一定差别。
> > > > > 简化驱动就将集显 / 网卡等安装时不必要的驱动先屏蔽掉，比如集显就直接用 `0x12345678` 进系统看看；网卡就先直接关闭相关的 kext。因为你这个我也不太确定是哪里的问题，只能先这样猜测性尝试下了……
> > > > 
> > > > 
> > > > 大佬，在帮助下找到了合适的 efi，非常感谢，还有一个问题想请教一下，我用 0.5.9 的 opencore 引导的时候第一项是叫 No Name， 下面才是 win 和 mac，请问能删除这个选项吗？
> > > 
> > > 
> > > No name 有没有可能是你插了带引导的 U 盘啥的…… Opencore 好像只能修改扫描磁盘的策略，而不能像 Clover 一样定向屏蔽某一盘符。
> > > 具体可以参考这篇文章的 `3.2` 部分：https://blog.xjn819.com/?p=543
> > 
> > 
> > 谢谢大佬，我研究一下。再问几个愚蠢的问题，在 10.15.5 之后的这些版本，hackintools 和 opencore 的主程序如何更新呢？kext 的更新只能用命令行吗？一般用什么在 mac 下面编辑 plist 比较好呢？感谢感谢！
> 
> 1. Hackintool 一般就正常更新就好了，这个没啥影响。
> 2. Opencore 在没有必要的情况下，我个人不太建议更新。因为目前的 OC 各版本间差异太大了，每次升级都要在 `config.plist` 上做很大的修改。所以如果能稳定使用了，且 OC 也没有什么重大改进了，我个人认为也就不太必要继续更新了。
> 3. kext 更新主要就是几个步骤：- 复制进 `\EFI\OC (或 Clover)\Kexts` - 在 OC 的 Config.plist 中添加并启用（Clover 就不需要了）  - 如果重启后不即时生效，Terminal 内清空缓存：`kextcache -i /`。
> 4. 如果你需要像 Clover 一样可视化地修改 config，可以在 https://mackie100projects.altervista.org/category/opencore-configurator-changelog/ 下载各版本的 `Opencore Configurator`，Changelog 里都会写支持的 OC 版本，注意对应就行了。或者你用 VSCode 啥的手动改也可以……

感谢大佬的耐心解答，辛苦大佬！
