### ISSUE TITLE
intel网卡，win1909蓝牙固件，蓝牙鼠标连不上

### ISSUE THREAD

**Issue by casper-kang** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#37]
环境如上
 
测试了罗技的master2s和戴尔的615，现象一致：连接上的瞬间就断了，然后就无法连接，需要重新开启鼠标蓝牙

**Comment by Pinming** [comment]
> 环境如上
> 
> 测试了罗技的master2s和戴尔的615，现象一致：连接上的瞬间就断了，然后就无法连接，需要重新开启鼠标蓝牙

23333 这个问题建议左转 https://github.com/zxystd/IntelBluetoothFirmware 向原作者提问了😂
