### ISSUE TITLE
启动一直卡logo界面

### ISSUE THREAD

**Issue by seepine** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#38]
烧写最新镜像到u盘，下最新版efi，将1080p的重命名为默认的config，不管放磁盘的efi启动，还是U盘的efi启动，进安装界面永远卡在logo界面，第一次卡10%，第二次卡70%左右，第三次第四次一直都在50%左右

**Comment by seepine** [comment]
使用tctien342大佬的efi，他的启动会有错误提示，发现卡在了这边，Olease switch to XPC or bootstrap_check_in():com.apple.bsd.dirhelper
![IMG_6348](https://user-images.githubusercontent.com/52092701/84731939-f6fa2800-afcc-11ea-945b-627f3b48fc95.JPG)

**Comment by liuziyuan15** [comment]
我是用clover安装，再切的oc，你可以试试

**Comment by Pinming** [comment]
这个 EFI 没有尝试过安装过程，不过 Recovery HD 倒是可以进去。
实在不行还是建议先 Clover 安装再迁移过来吧。
