### ISSUE TITLE
1820A又挂了...

### ISSUE THREAD

**Issue by Odysseusq** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#41]
第一次淘了个不好用退掉了，第二次咸鱼弄了个3T3的一样不好用，用了个把月到昨天就一整天不行了，今天还是不行，惨兮兮，用什么网卡才好啊...

**Comment by liuziyuan15** [comment]
不在乎随航和隔空投屏的话，自带的intel不就挺好的

**Comment by Liang-aj** [comment]
> 不在乎随航和隔空投屏的话，自带的intel不就挺好的

自带的可以用WIFI吗

**Comment by liuziyuan15** [comment]
@Liang-aj 可以的，最新版驱动连隔空投送都可以了，很舒服，去b站搜黑苹果 intel找最新的视频，简介里有驱动

**Comment by Pinming** [comment]
一整天不行是什么情况？如果是系统找不到网卡的话，建议拔插几下（有点玄学）。

**Comment by ahoneyboy** [comment]
> @Liang-aj 可以的，最新版驱动连隔空投送都可以了，很舒服，去b站搜黑苹果 intel找最新的视频，简介里有驱动

能正常使用吗？
