### ISSUE TITLE
安装intel power gadget之后的问题

### ISSUE THREAD

**Issue by LiangQinAo** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#43]
安装intel power gadget后
应该是某个驱动会失效之类的，如果有查看cpu睿频之类的软件，打开启动就会马上死机，不会自动恢复，
只能通过进入安全模式，把自启动的有关看睿频的软件都卸载掉或者关闭自启动才能解决这问题

**Comment by Pinming** [comment]
我这边没有出现啊…… 建议更换个版本试一下？

**Comment by Pinming** [comment]
我这边没有出现啊…… 建议更换个版本试一下？

**Comment by Liang-aj** [comment]
里面有玄学，现在正常使用了
