### ISSUE TITLE
4k机型显卡驱动不了

### ISSUE THREAD

**Issue by ahoneyboy** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#46]
4k夏普的7590顶配有没有朋友用这个装成功的，我的搞不定，能不能帮忙，非常感谢，主要显卡驱动不了

**Comment by Pinming** [comment]
请提供具体的 -v 图。
如果 EFI 不做改动的话应该还是能正常进去的…… 我也夏普 4K

**Comment by Irving-cmd** [comment]
> 4k夏普的7590顶配有没有朋友用这个装成功的，我的搞不定，能不能帮忙，非常感谢，主要显卡驱动不了

集成显卡理论上是可以驱动的，独立显卡还是别做梦了，具体定位问题，得开啰嗦模式看一下报错在哪

**Comment by Irving-cmd** [comment]
> 请提供具体的 -v 图。
> 如果 EFI 不做改动的话应该还是能正常进去的…… 我也夏普 4K

作者老哥，我的1080p外接还是闪屏，绝了，intel分支5.30版本

**Comment by ahoneyboy** [comment]
> 请提供具体的 -v 图。
> 
> 如果 EFI 不做改动的话应该还是能正常进去的…… 我也夏普 4K

重试了，可以进系统，就是在安装过程中有屏幕息屏但背景灯还是亮的。然后安装好后正常进系统每次在苹果logo加载时都会屏幕闪几下，进去桌面也是好的。谢谢作者的精心维护和分享。然后问下是不是dw1820a网卡都能用？

**Comment by ahoneyboy** [comment]
> > 4k夏普的7590顶配有没有朋友用这个装成功的，我的搞不定，能不能帮忙，非常感谢，主要显卡驱动不了
> 
> 
> 
> 集成显卡理论上是可以驱动的，独立显卡还是别做梦了，具体定位问题，得开啰嗦模式看一下报错在哪
> 
> 

成功进去了，谢谢
