### ISSUE TITLE
概率黑屏

### ISSUE THREAD

**Issue by lfpai** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#49]
能进入系统，大多数时候会黑屏，需要关盖子再打开 屏幕就显示了，如何解决

**Comment by ahoneyboy** [comment]
我也是一样的问题，尤其是在系统登录前或登录进入桌面的时候，概率非常大。电脑配置与版主一样的，除了ssd不一样外，而且也换了dw1820a网卡。

**Comment by lfpai** [comment]
> 我也是一样的问题，尤其是在系统登录前或登录进入桌面的时候，概率非常大。电脑配置与版主一样的，除了ssd不一样外，而且也换了dw1820a网卡。

我通过注入显卡id和edid，启动项加igfxonln=1，可以减小概率，你可以试试

**Comment by ahoneyboy** [comment]
> > 我也是一样的问题，尤其是在系统登录前或登录进入桌面的时候，概率非常大。电脑配置与版主一样的，除了ssd不一样外，而且也换了dw1820a网卡。
> 
> 
> 
> 我通过注入显卡id和edid，启动项加igfxonln=1，可以减小概率，你可以试试

注入后显卡能正常驱动吗，我是4k版，你的也是吗？怎么注入能否教授下，谢谢

**Comment by lfpai** [comment]
> > > 我也是一样的问题，尤其是在系统登录前或登录进入桌面的时候，概率非常大。电脑配置与版主一样的，除了ssd不一样外，而且也换了dw1820a网卡。
> > 
> > 
> > 我通过注入显卡id和edid，启动项加igfxonln=1，可以减小概率，你可以试试
> 
> 注入后显卡能正常驱动吗，我是4k版，你的也是吗？怎么注入能否教授下，谢谢

![Uploading image.png…]()
我也是4k

**Comment by lfpai** [comment]
> > > 我也是一样的问题，尤其是在系统登录前或登录进入桌面的时候，概率非常大。电脑配置与版主一样的，除了ssd不一样外，而且也换了dw1820a网卡。
> > 
> > 
> > 我通过注入显卡id和edid，启动项加igfxonln=1，可以减小概率，你可以试试
> 
> 注入后显卡能正常驱动吗，我是4k版，你的也是吗？怎么注入能否教授下，谢谢
我也是4k，在deviceproperties里找到显卡路径添加
