### ISSUE TITLE
HiDPI可以开启吗

### ISSUE THREAD

**Issue by 0ytian** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#5]
如题

**Comment by Pinming** [comment]
我是 4K 机 一切正常…… 有同学测试了 1080 也应该是能用

**Comment by Irving-cmd** [comment]
1080p的可能不行，我是cmn15f6的屏幕，能调节分辨率，但不是hidpi那种

**Comment by 0ytian** [comment]
@Irving-cmd 我开启了，但是开机logo会放大，其他倒没什么问题，还能接受

**Comment by Irving-cmd** [comment]
用什么方式呢，脚本？那个改显示器id的？，能不能指个路

**Comment by 0ytian** [comment]
@Irving-cmd https://www.sqlsec.com/2018/09/hidpi.html

**Comment by Pinming** [comment]
> @Irving-cmd 我开启了，但是开机logo会放大，其他倒没什么问题，还能接受

开机 Logo 我的 config 应该调过了呀…… 将 `UIScale` 值改为 `01` 就不会有大苹果

**Comment by 0ytian** [comment]
@Pinming 我也不太清楚，用了脚本开启HiDPI之后，开机logo会在加载到一半的时候变大

**Comment by Pinming** [comment]
> @Pinming 我也不太清楚，用了脚本开启HiDPI之后，开机logo会在加载到一半的时候变大

`UIScale` 只能决定开机第一阶段的 Logo 大小。至于第二阶段的话应该就是根据 HiDPI 自行决定的…… 不过这机器不应该原生支持 HiDPI 嘛
对于 1080P 机型来说，`UIScale = 01` 应该就是标准的大小。当然如果你有强迫症可以自己改改看让两个一样大 233333

**Comment by Irving-cmd** [comment]
> @Irving-cmd https://www.sqlsec.com/2018/09/hidpi.html

我用他那个脚本一直显示连不上gayhub那个库，这几天科学上网又坏了，就很烦

**Comment by 0ytian** [comment]
@Pinming emmm， 开启HiDPI只能到1440x800分辨率，屏幕放大了很多，有点受不了又改回默认了2333。后悔当初没有加钱上4k顶配版

**Comment by Irving-cmd** [comment]
不要保修你可以自己换啊😏




| |
赵欧文
|
|
邮箱：13505788985@163.com
|

签名由 网易邮箱大师 定制

在2020年03月16日 11:24，0uyangtian 写道：

@Pinming emmm， 开启HiDPI只能到1440x800分辨率，屏幕放大了很多，有点受不了又改回默认了2333。后悔当初没有加钱上4k顶配版

**Comment by 0ytian** [comment]
@Pinming 😂那我先用多一段时间，用残了再折腾，没有保修也不心疼

**Comment by 0ytian** [comment]
@Irving-cmd 😂那我先用多一段时间，用残了再折腾，没有保修也不心疼

**Comment by 0ytian** [comment]
> > @Irving-cmd https://www.sqlsec.com/2018/09/hidpi.html
> 
> 我用他那个脚本一直显示连不上gayhub那个库，这几天科学上网又坏了，就很烦

github还好吧，虽然慢但是还是有网速的，本来那个repo也不大

**Comment by Irving-cmd** [comment]
我提示curl35，一直连不上，挂梯子也没用
