### ISSUE TITLE
7590 睡眠问题

### ISSUE THREAD

**Issue by cassius425** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#52]
大佬，就按照@tcticen342大神的7591的睡眠部分代码，执行到最后一个 sudo pmset -b tcpkeepalive 0 (optional)  提示 zsh: unknown sort specifier 是什么情况呢，前边几个都没有问题，你那边是如何解决的呢

**Comment by Pinming** [comment]
![image](https://user-images.githubusercontent.com/30550234/87315310-f1a1e600-c556-11ea-9196-b7795cb9ab81.png)
我这边为了降压 CPU 所以关闭了所谓原生电源管理…… 因此是没有这个设置项的。所以不太清楚 2333

**Comment by Liang-aj** [comment]
> ![image](https://user-images.githubusercontent.com/30550234/87315310-f1a1e600-c556-11ea-9196-b7795cb9ab81.png)
> 我这边为了降压 CPU 所以关闭了所谓原生电源管理…… 因此是没有这个设置项的。所以不太清楚 2333

关闭原生电源管理是为了降压CPU？为什么？

**Comment by Pinming** [comment]
> > ![image](https://user-images.githubusercontent.com/30550234/87315310-f1a1e600-c556-11ea-9196-b7795cb9ab81.png)
> > 我这边为了降压 CPU 所以关闭了所谓原生电源管理…… 因此是没有这个设置项的。所以不太清楚 2333
> 
> 关闭原生电源管理是为了降压CPU？为什么？

不关那个的话用不了 VoltageShift 啊 233

**Comment by Liang-aj** [comment]
> > > ![image](https://user-images.githubusercontent.com/30550234/87315310-f1a1e600-c556-11ea-9196-b7795cb9ab81.png)
> > > 我这边为了降压 CPU 所以关闭了所谓原生电源管理…… 因此是没有这个设置项的。所以不太清楚 2333
> > 
> > 
> > 关闭原生电源管理是为了降压CPU？为什么？
> 
> 不关那个的话用不了 VoltageShift 啊 233
> 而且感觉关掉之后对于性能调用没有很大的影响，该凉的时候也不会发热。

我开着，也可以用Voltageshift 2？降压设置如图
![Uploading Snipaste_2020-07-14_16-26-48.png…]()

**Comment by Liang-aj** [comment]
------------------------------------------------------
   VoltageShift Info Tool
------------------------------------------------------
WRMSR 150 with value 0x8000001000000000
RDMSR 150 returns value 0xf0600000
CPU voltage offset: -125mv
WRMSR 150 with value 0x8000011000000000
RDMSR 150 returns value 0xf4c00000
GPU voltage offset: -90mv
WRMSR 150 with value 0x8000021000000000
RDMSR 150 returns value 0xf0600000
CPU Cache voltage offset: -125mv
WRMSR 150 with value 0x8000031000000000
RDMSR 150 returns value 0x0
System Agency offset: 0mv
WRMSR 150 with value 0x8000041000000000
RDMSR 150 returns value 0x0
Analogy I/O: 0mv
WRMSR 150 with value 0x8000051000000000
OC mailbox cmd failed
RDMSR 150 returns value 0x500000000
Digital I/O: 0mv
CPU BaseFreq: 2600, CPU MaxFreq(1/2/4/6): 4500/4400/4200/4000 (mhz) 
  PL1: 45W PL2: 90W 
CPU Freq: 2.5ghz, Voltage: 0.7980v, Power:pkg 19.81w /core 13.60w,Temp: 64 c
aoliang@AodeMacBook-Pro Voltageshift 2 %

**Comment by Pinming** [comment]
啊这……那我就不是很清楚了→_→之前 kawauso 写的那篇文章说不行
这样的话 你这个问题我确实不太清楚咋解决【捂脸】

**Comment by Liang-aj** [comment]
我的是这样的


Last login: Tue Jul 14 16:26:29 on ttys001
aoliang@AodeMacBook-Pro ~ % sudo pmset -g
Password:
System-wide power settings:
Currently in use:
 standbydelaylow      10800
 standby              1
 womp                 1
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 proximitywake        1
 powernap             0
 networkoversleep     0
 disksleep            10
 standbydelayhigh     86400
 sleep                10 (sleep prevented by sharingd, UserEventAgent, UserEventAgent, coreaudiod, coreaudiod)
 hibernatemode        3
 ttyskeepawake        1
 displaysleep         10
 tcpkeepalive         1
 highstandbythreshold 50
 acwake               0
 lidwake              1
aoliang@AodeMacBook-Pro ~ %

**Comment by cassius425** [comment]
> 我的是这样的
> 
> Last login: Tue Jul 14 16:26:29 on ttys001
> aoliang@AodeMacBook-Pro ~ % sudo pmset -g
> Password:
> System-wide power settings:
> Currently in use:
> standbydelaylow 10800
> standby 1
> womp 1
> halfdim 1
> hibernatefile /var/vm/sleepimage
> proximitywake 1
> powernap 0
> networkoversleep 0
> disksleep 10
> standbydelayhigh 86400
> sleep 10 (sleep prevented by sharingd, UserEventAgent, UserEventAgent, coreaudiod, coreaudiod)
> hibernatemode 3
> ttyskeepawake 1
> displaysleep 10
> tcpkeepalive 1
> highstandbythreshold 50
> acwake 0
> lidwake 1
> aoliang@AodeMacBook-Pro ~ %

大佬，你遇到过睡眠后，唤醒屏幕不亮的情况吗？或者你那睡眠是如何修复的

**Comment by Liang-aj** [comment]
> > 我的是这样的
> > Last login: Tue Jul 14 16:26:29 on ttys001
> > aoliang@AodeMacBook-Pro ~ % sudo pmset -g
> > Password:
> > System-wide power settings:
> > Currently in use:
> > standbydelaylow 10800
> > standby 1
> > womp 1
> > halfdim 1
> > hibernatefile /var/vm/sleepimage
> > proximitywake 1
> > powernap 0
> > networkoversleep 0
> > disksleep 10
> > standbydelayhigh 86400
> > sleep 10 (sleep prevented by sharingd, UserEventAgent, UserEventAgent, coreaudiod, coreaudiod)
> > hibernatemode 3
> > ttyskeepawake 1
> > displaysleep 10
> > tcpkeepalive 1
> > highstandbythreshold 50
> > acwake 0
> > lidwake 1
> > aoliang@AodeMacBook-Pro ~ %
> 
> 大佬，你遇到过睡眠后，唤醒屏幕不亮的情况吗？或者你那睡眠是如何修复的

没有哦，我是直接用大佬的eif的，睡眠没有问题，自己开启了那个原生电源管理，也没有什么问题

**Comment by cassius425** [comment]
> > > 我的是这样的
> > > Last login: Tue Jul 14 16:26:29 on ttys001
> > > aoliang@AodeMacBook-Pro ~ % sudo pmset -g
> > > Password:
> > > System-wide power settings:
> > > Currently in use:
> > > standbydelaylow 10800
> > > standby 1
> > > womp 1
> > > halfdim 1
> > > hibernatefile /var/vm/sleepimage
> > > proximitywake 1
> > > powernap 0
> > > networkoversleep 0
> > > disksleep 10
> > > standbydelayhigh 86400
> > > sleep 10 (sleep prevented by sharingd, UserEventAgent, UserEventAgent, coreaudiod, coreaudiod)
> > > hibernatemode 3
> > > ttyskeepawake 1
> > > displaysleep 10
> > > tcpkeepalive 1
> > > highstandbythreshold 50
> > > acwake 0
> > > lidwake 1
> > > aoliang@AodeMacBook-Pro ~ %
> > 
> > 
> > 大佬，你遇到过睡眠后，唤醒屏幕不亮的情况吗？或者你那睡眠是如何修复的
> 
> 没有哦，我是直接用大佬的eif的，睡眠没有问题，自己开启了那个原生电源管理，也没有什么问题

我替换下试试呢。

**Comment by cassius425** [comment]
通过hackintool 打补丁修复
