### ISSUE TITLE
【DW1820A】蓝牙无法连接AirPods

### ISSUE THREAD

**Issue by cliche9** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#53]
1. 关闭wifi，单独打开蓝牙扫描不到AirPods. 
2. 打开wifi，打开蓝牙能扫描到AirPods，但是要么连接后播放声音断断续续，要么点击连接无反应，无法连接.

**Comment by Pinming** [comment]
https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html
可以参考一下黑果小兵的文章更换其他版本的驱动试试。
另外 2.4Ghz 的 WIFI 有可能和蓝牙有干扰.. 不知道跟这个有没有关系

**Comment by cliche9** [comment]
> https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html
> 可以参考一下黑果小兵的文章更换其他版本的驱动试试。
> 另外 2.4Ghz 的 WIFI 有可能和蓝牙有干扰.. 不知道跟这个有没有关系

改成黑果小兵的蓝牙kext文件后解决了第一个问题，蓝牙连接也更顺畅了，不过wifi和蓝牙干扰问题确实无解，还是得连5g频段wifi，顺便问一下，原efi中的wifi驱动需要更新吗，是否有新版了呢？

**Comment by Pinming** [comment]
> > https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html
> > 可以参考一下黑果小兵的文章更换其他版本的驱动试试。
> > 另外 2.4Ghz 的 WIFI 有可能和蓝牙有干扰.. 不知道跟这个有没有关系
> 
> 改成黑果小兵的蓝牙kext文件后解决了第一个问题，蓝牙连接也更顺畅了，不过wifi和蓝牙干扰问题确实无解，还是得连5g频段wifi，顺便问一下，原efi中的wifi驱动需要更新吗，是否有新版了呢？

`AirportBrcmFixup` 最近一次更新在昨天。
主要是我自己平常不用蓝牙耳机…… 所以这个问题我也没啥办法测试，建议自己编译更新一下吧😄
需要注意的是：自 7 月 5 日后更新的版本驱动方式有变，可能需要更改 config.plist 中 `boot-args` 的网卡相关内容。
具体可参阅本文：http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1863868&

**Comment by cliche9** [comment]
> > > https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html
> > > 可以参考一下黑果小兵的文章更换其他版本的驱动试试。
> > > 另外 2.4Ghz 的 WIFI 有可能和蓝牙有干扰.. 不知道跟这个有没有关系
> > 
> > 
> > 改成黑果小兵的蓝牙kext文件后解决了第一个问题，蓝牙连接也更顺畅了，不过wifi和蓝牙干扰问题确实无解，还是得连5g频段wifi，顺便问一下，原efi中的wifi驱动需要更新吗，是否有新版了呢？
> 
> `AirportBrcmFixup` 最近一次更新在昨天。我个人倾向于不影响正常使用就不要更新 kext 了.. 不然更新来更新去一旦失效了又很麻烦。
> 然后我自己也平常不用蓝牙耳机…… 所以这个问题我也没啥办法测试，如果确实有必要建议自行编译更新一下吧😄
> （对 10.15 系统，以下部分应该不用看；10.16 这里是有变化的）
> 需要注意的是：自 7 月 5 日后更新的版本驱动方式有变，可能需要更改 config.plist 中 `boot-args` 的网卡相关内容。
> 具体可参阅本文：http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1863868&

Thanks，非常感谢，也非常感谢整个EFI文件的调试和分享！
