### ISSUE TITLE
大佬可以看看这个EFI把里面的风扇驱动提取出来吗

### ISSUE THREAD

**Issue by Liang-aj** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#54]
我的7591测了一下，可以正常开机，但是WIFI没法用，关机也不正常，但是风扇监控，调节这些是正常的。
如果可以整合到我们的EFI里面去就好了
链接: https://pan.baidu.com/s/1qsyCMjsWBNc3GD0QhH3lqA 提取码: 7bti

**Comment by lfpai** [comment]
我试了试你分享的efi只要把smcdellsensoes.kext 加入pinming的efi中就可以显示风扇转速

**Comment by lfpai** [comment]
<img width="364" alt="截屏2020-07-15 下午1 11 26" src="https://user-

**Comment by lfpai** [comment]
<img width="364" alt="截屏2020-07-15 下午1 11 26" src="https://user-images.githubusercontent.com/60920607/87506286-83b40680-c69d-11ea-88d9-8f61f64ea772.png">

**Comment by Liang-aj** [comment]
> 我试了试你分享的efi只要把smcdellsensoes.kext 加入pinming的efi中就可以显示风扇转速

感谢，按照你说得做，我也可以了
