### ISSUE TITLE
[7591 ] I7-9750H 主频不会提升问题

### ISSUE THREAD

**Issue by Liang-aj** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#56]
![frequency](https://user-images.githubusercontent.com/52418688/87670929-1ee2d400-c7a3-11ea-8f8d-37fb9f67ad9c.png)

无论我运行什么，主频基本都不会上到3g以上，只有刚开机的时候睿频正常，之后就一直保持2.6g左右，明明温度也没有撞温度墙，请问知道是什么原因吗

**Comment by Pinming** [comment]
检查一下 cpu 相关 kext 都打开了没有吧.. 这个问题我没有碰到过，不好下定论

**Comment by hhaacnmb111** [comment]
是不是开启了HWPEnabler.kext？之前尝试过，我的i5-9300h在开启之前最高4.0G，开启之后最高只有3.0G。

**Comment by Liang-aj** [comment]
> 是不是开启了HWPEnabler.kext？之前尝试过，我的i5-9300h在开启之前最高4.0G，开启之后最高只有3.0G。

谢谢回复。
检查了一下，并没有开启，我重启之后可以睿频到3g以上，但是用一段时间就会锁到2.6g左右，目前还不知道什么原因

**Comment by Liang-aj** [comment]
> 检查一下 cpu 相关 kext 都打开了没有吧.. 这个问题我没有碰到过，不好下定论

重启之后会恢复正常，但是用一段时间又会锁，即使占用50%以上，主频还是不会提高，一直在2.4g-2.7g徘徊，所以导致很卡，温度60度左右，功耗只有25w。
kext最近动过的只有添加了一个 SMCDellSensors.kext，风扇的驱动，其他没变化过

**Comment by hhaacnmb111** [comment]
> > 检查一下 cpu 相关 kext 都打开了没有吧.. 这个问题我没有碰到过，不好下定论
> 
> 重启之后会恢复正常，但是用一段时间又会锁，即使占用50%以上，主频还是不会提高，一直在2.4g-2.7g徘徊，所以导致很卡，温度60度左右，功耗只有25w。
> kext最近动过的只有添加了一个 SMCDellSensors.kext，风扇的驱动，其他没变化过

你添加了smcdellsensor.kext有用吗？我这边macsfancontrol还是显示reset smc。。。

**Comment by Liang-aj** [comment]
> > > 检查一下 cpu 相关 kext 都打开了没有吧.. 这个问题我没有碰到过，不好下定论
> > 
> > 
> > 重启之后会恢复正常，但是用一段时间又会锁，即使占用50%以上，主频还是不会提高，一直在2.4g-2.7g徘徊，所以导致很卡，温度60度左右，功耗只有25w。
> > kext最近动过的只有添加了一个 SMCDellSensors.kext，风扇的驱动，其他没变化过
> 
> 你添加了smcdellsensor.kext有用吗？我这边macsfancontrol还是显示reset smc。。。

我添加，然后勾选一下，就直接可以用了

**Comment by hhaacnmb111** [comment]
> > > > 检查一下 cpu 相关 kext 都打开了没有吧.. 这个问题我没有碰到过，不好下定论
> > > 
> > > 
> > > 重启之后会恢复正常，但是用一段时间又会锁，即使占用50%以上，主频还是不会提高，一直在2.4g-2.7g徘徊，所以导致很卡，温度60度左右，功耗只有25w。
> > > kext最近动过的只有添加了一个 SMCDellSensors.kext，风扇的驱动，其他没变化过
> > 
> > 
> > 你添加了smcdellsensor.kext有用吗？我这边macsfancontrol还是显示reset smc。。。
> 
> 我添加，然后勾选一下，就直接可以用了
更新一下，我后来用了istat menu可以正常识别和调节风扇，但是Macsfancontrol不行。
