### ISSUE TITLE
7.16版增加的风扇转速功能不能使用

### ISSUE THREAD

**Issue by ahoneyboy** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#57]
用的7.16efi版本，系统mac 10.15.6，mac fan软件中显示需要重置smc，不知道怎么解决？

**Comment by Pinming** [comment]
建议使用 iStat Menus。
Mac Fan Control 据说会影响机器睡眠……我自己也没有使用那个

**Comment by hhaacnmb111** [comment]
> 建议使用 iStat Menus。
> Mac Fan Control 据说会影响机器睡眠……我自己也没有使用那个

用istat menus之后，睡眠唤醒会黑屏，Macsfancontrol好像没问题
