### ISSUE TITLE
7590 1080P下不知道为什么外接显示器会闪屏，windows下没有问题，还有这个显示器也能识别

### ISSUE THREAD

**Issue by wscaiyang** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#58]

**Comment by wscaiyang** [comment]
下午回去准备换个显示器或者hdmi线试一下

**Comment by Pinming** [comment]
是 `20.7.16` 版吗？如果是老版本，请参见 `20.7.16` 版的更新日志。应该这样是能解决闪屏的，不过会牺牲 HDMI 音频输出

> 这样的异常可以通过使机器睡眠再唤醒而暂时解决。
对于 1080P 机型，输出声音与否通过 `DeviceProperties->PciRoot(0x0)/Pci(0x1f,0x3)` 中 `alc-device-id` 和 `alc-vendor-id` 的开闭来控制。如果不注入这两个参数则 HDMI 不会输出声音。
鉴于有一定数量朋友反馈输出声音会导致 HDMI 输出异常，自 20.7.16 版本起，这两个参数在 1080P 机型配置文件下默认被注释（即默认不输出声音）。如果愿意尝试，可以尝试去除条目前的 # 号开启这两个参数，当然并不保证能够成功，请自行测试。

**Comment by lyon232** [comment]
> 下午回去准备换个显示器或者hdmi线试一下

同1080P,同样问题，解决方法：注释DeviceProperties->PciRoot(0x0)/Pci(0x1f,0x3) 中 alc-device-id 和 alc-vendor-id， 0716版代码可能是忘记更新了， 代码与文档不一致

**Comment by Pinming** [comment]
> > 下午回去准备换个显示器或者hdmi线试一下
> 
> 同1080P,同样问题，解决方法：注释DeviceProperties->PciRoot(0x0)/Pci(0x1f,0x3) 中 alc-device-id 和 alc-vendor-id， 0716版代码可能是忘记更新了， 代码与文档不一致
> [#58 (comment)](https://github.com/Pinming/Dell-Inspiron-7590-Hackintosh-Opencore/issues/58#issuecomment-663834465)

感谢提醒，已修复。
