### ISSUE TITLE
7591 GPU突然锁频最高的问题

### ISSUE THREAD

**Issue by Liang-aj** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#59]
![Snipaste_2020-07-22_16-58-19](https://user-images.githubusercontent.com/52418688/88156835-8e8e0e80-cc3c-11ea-9483-808be9ed55e7.png)

如图，一直锁定到最高频率1.15g
只能重启解决，有一定几率遇到这个问题

不知你们有没有遇到过

**Comment by Pinming** [comment]
使用 Apple Guc Firmware 确实有可能出现这个问题。
如果出现频率确实无法接受，可以自行删去 `igfxfw=2` 启动参数。
