### ISSUE TITLE
系统安装

### ISSUE THREAD

**Issue by 0ytian** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#6]
可以给个大概的安装过程吗？我最近打算重装macos，但是按照黑果小兵上面的教程死活识别不出来我的安装U盘

**Comment by Pinming** [comment]
建议另外自己换一个 Opencore 或 Clover 并写入 EFI…… 或者干脆换镜像 我用黑果小兵的也会读不到 U 盘

**Comment by 0ytian** [comment]
@Pinming 有其他网站可以下载镜像吗？我看很多网站都是直接引用了黑果小兵的镜像

**Comment by Pinming** [comment]
> @Pinming 有其他网站可以下载镜像吗？我看很多网站都是直接引用了黑果小兵的镜像

我个人用的 `osx.cx` 家的镜像，感觉还可以，不过这论坛注册收费。
远景 `Len's` 家的貌似也还行……
