### ISSUE TITLE
windows10 开启hyper-v之后使用oc 引导蓝屏，换成windows 自带引导可以正常进系统

### ISSUE THREAD

**Issue by viewhang** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#62]
windows10 开启hyper-v之后使用oc 引导蓝屏，换成windows 自带引导可以正常进系统

**Comment by Lolioy** [comment]
@viewhang 用OC还开hyperv会出问题的

**Comment by jujuchao** [comment]
我昨天也遇到了，我锐龙bios内关闭svm或者换自带引导进就可以

**Comment by mxm646690173** [comment]
大佬，求帮忙解决个问题，我用OC引导，引导到一半就自动重启，没法进安装页面，镜像15.7到15.3 都试过一次了
![fe29ebb11ad5cb28734ab2983fee619](https://user-images.githubusercontent.com/57613270/96696881-dc422080-13bd-11eb-9e85-c095b9ff89b1.jpg)
![dec686fa6770b64c29c07622683ad17](https://user-images.githubusercontent.com/57613270/96696901-e2380180-13bd-11eb-9d03-29375cbeef48.jpg)

**Comment by TIMhao** [comment]
回答楼主#62的问题：windows10 开启hyper-v之后使用oc 引导蓝屏，换成windows 自带引导可以正常进系统
解决方法：（修改OC引导config.plist文件）
Boot -> Quirks -> SyncRuntimePermissions = True
