### ISSUE TITLE
OC无法识别Big sur 启动盘

### ISSUE THREAD

**Issue by lcyf9102s** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#63]
新分区安装Big Sur b4，与10.15共存。不管是使用10.15的引导还是Big Sur的引导，在第一阶段macOS installer安装完重启后OC界面并没有显示Big Sur启动盘。

**Comment by lcyf9102s** [comment]
更正一下，装的是public beta，不是beta 4。换成更新前的bigsur引导，并且在10.15.6上覆盖安装没有问题。

**Comment by Pinming** [comment]
感谢反馈。
可以尝试一下在 `BlessOverride` 项中加入：
```
\System\Library\CoreServices\boot.efi
```
我这边的话如果是 OTA 升级，不加这个也是能读到安装盘的。

安装完成以后建议删去该项，否则可能导致启动项出现重复。

**Comment by Pinming** [comment]
> 感谢反馈。
> 可以尝试一下在 `BlessOverride` 项中加入：
> 
> ```
> \System\Library\CoreServices\boot.efi
> ```
> 
> 我这边的话如果是 OTA 升级，不加这个也是能读到安装盘的。
> 
> 安装完成以后建议删去该项，否则可能导致启动项出现重复。
> 
> PB1 和 DB4 应该我估计是差不多的…… 小版本号都是 `5343`。

想起来一点…… OpenCore 是最新的版本吗？建议更新到最近的版本，这个问题应该是有修复的。我这边用的 8 月 7 日的版本能看到启动项。

**Comment by lcyf9102s** [comment]
> > 感谢反馈。
> 
> > 可以尝试一下在 `BlessOverride` 项中加入：
> 
> > 
> 
> > ```
> 
> > \System\Library\CoreServices\boot.efi
> 
> > ```
> 
> > 
> 
> > 我这边的话如果是 OTA 升级，不加这个也是能读到安装盘的。
> 
> > 
> 
> > 安装完成以后建议删去该项，否则可能导致启动项出现重复。
> 
> > 
> 
> > PB1 和 DB4 应该我估计是差不多的…… 小版本号都是 `5343`。
> 
> 
> 
> 想起来一点…… OpenCore 是最新的版本吗？建议更新到最近的版本，这个问题应该是有修复的。我这边用的 8 月 7 日的版本能看到启动项。

感谢大佬🙏，两种方法都试过了，都没问题。
