### ISSUE TITLE
额，为什么我现在从oc启动就是黑频 f12选oc就会进入自检

### ISSUE THREAD

**Issue by liuziyuan15** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#65]
如题，以前是正常的，因为某些原因有一段时间没用黑果，最近格了硬盘重装系统就这样了。

**Comment by Lolioy** [comment]
估计是引导丢了，建议重新弄引导

**Comment by liuziyuan15** [comment]
> 估计是引导丢了，建议重新弄引导

没，试了下，最新的oc我用不了，用大佬期末考之前的就可以，而无论怎样从f12选都会进自检，但是设置顺位第一自启动就不会。
