### ISSUE TITLE
关于风扇的问题

### ISSUE THREAD

**Issue by Klnsm** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#68]
最近7.16更新显示更新了DellSMCSensor，可以用iStat Menus控制风扇，但是我安装了iStat Menus后根本没有风扇的选项，
目前充着电看视频温度都能飙升到100左右，风扇纹丝不动，希望大佬回复下为什么？是不是DellSMCSensor又移除了。
感谢！
![2661C47481B71DD6CAA7565AD2CE9697](https://user-images.githubusercontent.com/50707483/90501507-0e958e80-e17f-11ea-8de2-7e994a90006d.jpg)

**Comment by YANGHAI666** [comment]
同问

**Comment by Pinming** [comment]
应该是我的 master 分支忘记加上去了【捂脸】
感谢反馈，明天加上去。或者可以自行更新一下最新版的 VirtualSMC 也行……
