### ISSUE TITLE
OpenCore config.plist 编辑器问题

### ISSUE THREAD

**Issue by 0ytian** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#7]
最近用 OpenCore Configurator 去编辑 config.plist，然后 OpenCore Boot(OCB) 就挂掉了，因为之前一直用来编辑隔壁 @tctien342 的配置文件没什么问题的，这个问题搞了大半天才找到问题。想问一下大佬是用什么来编辑的？

**Comment by Pinming** [comment]
目前 OpenCore Configurator 对于 `0.5.6` 版本支持不是太好，因为这一版的 `config.plist` 在结构上进行了大量修改。
建议使用`XCode` 或 `Plist Editor` 手动改参数。
听说 OCC 最近也更新了好像支持新版本 OC 了，不过我没尝试过→_→

**Comment by Pinming** [comment]
可以试一下新版的 OCC：https://shuiyunxc.gitee.io/2020/03/06/Faults/index/OpenCore-Configurator.zip
