### ISSUE TITLE
各种问题汇总，求解答

### ISSUE THREAD

**Issue by Chris51498** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#74]
1.睡眠经常睡死了直接，唤醒后，键盘鼠标都无法使用。
2.关机，开机时间很长（即使在关机前将所有的应用关闭）
3.无法登陆facetime 信息 appstore应用但是appleid可以登陆
4.隔空投递无法使用

**Comment by Pinming** [comment]
1) 请问一下是 10.15 还是 11.0 的系统呢……
2) 我个人这边没发现什么异常；
3) 建议重置一下白果三码。Facetime 需要联系苹果客服才能解锁应该
4) 英特尔网卡目前应该是不行的；博通网卡我手头没有苹果设备，所以测试不了

**Comment by Chris51498** [comment]
是11.0系统，其实其他的使用不了也都无所谓了。就是第一个问题是痛点，望大佬解决

**Comment by Pinming** [comment]
> 是11.0系统，其实其他的使用不了也都无所谓了。就是第一个问题是痛点，望大佬解决

尝试更新下 `CPUTSCSync` 吧…… 因为我这边的话三月份以后都没发现这个问题了，应该是个体差异吧

**Comment by Chris51498** [comment]
1.洗白了之后 app store可以登录，但是facetime和信息还是不能用。
2.更新了CPUTSCSync 之后，没有感受到什么改变，还是会睡死。正常启动后，扬声器有时还会不驱动；
3.跑微服务，一瞬间风扇起飞。温控软件显示99度，不知道要不要调低一点频率，安不安全呢

**Comment by lcyf9102s** [comment]
> 1.洗白了之后 app store可以登录，但是facetime和信息还是不能用。
> 
> 2.更新了CPUTSCSync 之后，没有感受到什么改变，还是会睡死。正常启动后，扬声器有时还会不驱动；
> 
> 3.跑微服务，一瞬间风扇起飞。温控软件显示99度，不知道要不要调低一点频率，安不安全呢

1. FaceTime imassage 需要network interface 有eth0
2. （Big Sur beta 7 不清楚）beta 6 和之前的经常会睡死。beta 8 基本上没问题。
3. cpu温度高可以用voltageshift降压。

**Comment by Chris51498** [comment]
> > 1.洗白了之后 app store可以登录，但是facetime和信息还是不能用。
> > 2.更新了CPUTSCSync 之后，没有感受到什么改变，还是会睡死。正常启动后，扬声器有时还会不驱动；
> > 3.跑微服务，一瞬间风扇起飞。温控软件显示99度，不知道要不要调低一点频率，安不安全呢
> 
> 1. FaceTime imassage 需要network interface 有eth0
> 2. （Big Sur beta 7 不清楚）beta 6 和之前的经常会睡死。beta 8 基本上没问题。
> 3. cpu温度高可以用voltageshift降压。

20A5364e 这应该是beta6吧  我用尝鲜派和betafile都没办法更新  ，12.16g的全量更新。快下载完毕就会说无法下载很烦

**Comment by lcyf9102s** [comment]
> > > 1.洗白了之后 app store可以登录，但是facetime和信息还是不能用。
> 
> > > 2.更新了CPUTSCSync 之后，没有感受到什么改变，还是会睡死。正常启动后，扬声器有时还会不驱动；
> 
> > > 3.跑微服务，一瞬间风扇起飞。温控软件显示99度，不知道要不要调低一点频率，安不安全呢
> 
> > 
> 
> > 1. FaceTime imassage 需要network interface 有eth0
> 
> > 2. （Big Sur beta 7 不清楚）beta 6 和之前的经常会睡死。beta 8 基本上没问题。
> 
> > 3. cpu温度高可以用voltageshift降压。
> 
> 
> 
> 20A5364e 这应该是beta6吧  我用尝鲜派和betafile都没办法更新  ，12.16g的全量更新。快下载完毕就会说无法下载很烦

把config.json里nvram中csr-active-config值改为00000000，应该可以正常更新了。beta 6以上的系统苹果没放在sucatalog，所以只能通过普通的系统更新。
