### ISSUE TITLE
G7-7590 聲卡是ALC263!!

### ISSUE THREAD

**Issue by Jakevin** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#76]
~~Dell G7 7590 用的是 ALC295的聲卡。~~

Dell G7 7590 是用 ALC236

請問想更換聲卡的話，有哪些參數需要調整的呢？

感謝！

**Comment by Pinming** [comment]
> Dell G7 7590 用的是 ALC295的聲卡。
> 
> 請問想更換聲卡的話，有哪些參數需要調整的呢？
> 
> 感謝！

Dell 的 ALC295 实际上应该是定制型号 ALC3254，和 Ins 7590 应该一致。理论上不需要更换其中参数。

**Comment by Jakevin** [comment]
感謝！
的確，應該是一樣才對，但我用了所有黑果小兵 75xx的OC檔，沒有一個可以成功開啟聲卡

目前朝向layout id 1~77 常用的id 全部試一次

**Comment by Jakevin** [comment]
> > Dell G7 7590 用的是 ALC295的聲卡。
> > 請問想更換聲卡的話，有哪些參數需要調整的呢？
> > 感謝！
> 
> Dell 的 ALC295 实际上应该是定制型号 ALC3254，和 Ins 7590 应该一致。理论上不需要更换其中参数。

解決了，原因居然是 layout-id 要用 53的 ALC263
