### ISSUE TITLE
请教大佬，如何从0开始使用这份EFI引导黑苹果

### ISSUE THREAD

**Issue by seepine** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#8]
目前我有两个磁盘，分别安装有win10和clover引导的黑苹果
请问如何改成openCore引导呢，抹除原黑苹果系统也没关系

**Comment by seepine** [comment]
我目前下载到了0.5.7-REKEASE压缩包，里面包含Docs、EFI、Utilities这三个目录，但是我不知道下一步我应该做什么了

**Comment by seepine** [comment]
在EFI目录中有BOOT和OC目录，是否将这个放到电脑的EFI中，启动的时候使用OC/OpenCore.efi来引导

**Comment by seepine** [comment]
我尝试将OC目录拷贝到电脑到EFI中，然后克隆您到EFI，将其覆盖到OC中，然后系统启动选择opencore.efi启动，能够看到界面且能够选择要启动到系统，当我选择之前所安装当黑苹果系统时，屏幕上出现一个苹果logo，但是卡了很久，logo下没有读条，不得已只能强制关机重启，请问我有哪个步骤出错了吗？

**Comment by Pinming** [comment]
如果你直接覆盖了 clover 的各个文件夹的话，那么不能启动应该是很正常的😂因为二者的大多数文件虽然结构类似但不互通。
建议新开一个 efi 并完全抛弃 clover 再重试一次吧……这个情况我觉得不一定要重装

**Comment by seepine** [comment]
> 如果你直接覆盖了 clover 的各个文件夹的话，那么不能启动应该是很正常的😂因为二者的大多数文件虽然结构类似但不互通。
> 建议新开一个 efi 并完全抛弃 clover 再重试一次吧……这个情况我觉得不一定要重装

不是哦，实际上我的操作是在clover同级新建了OC目录，将你的efi全部放进去，
![image](https://user-images.githubusercontent.com/52092701/77616824-8adbcb00-6f6d-11ea-9c7b-86485e1a8a98.png)
最终进bios将OC目录中的OpenCore.efi添加为一个启动项，然后用这个启动项启动

**Comment by seepine** [comment]
新开一个EFI指的是将本来磁盘中的EFI内容全部删掉，然后只放OC进去吗？

**Comment by Pinming** [comment]
> 新开一个EFI指的是将本来磁盘中的EFI内容全部删掉，然后只放OC进去吗？

如果是你说的这样那就不必删除其他内容了…… 这样子的话如果确实有必要还是重装一遍吧
但是我这边的话从 Clover 直接转向 OC 也没有问题 你是 1080P 还是 4K 呢

**Comment by seepine** [comment]
我是1080P，i7，我下你的EFI，然后把config.plist删掉，config-1080P.plist重命名为config.plist，这个操作对吗

**Comment by seepine** [comment]
哦对了，我的WIFI换成了1820A，这个有影响吗

**Comment by seepine** [comment]
```
本 config 对于无线网卡及蓝牙的默认操作：
默认加载 IntelBluetoothFirmware；默认将 Broadcom 无线网卡的各项驱动安置在 \OC\kexts 文件夹中但不启用。
如果已经更换了 Broadcom 无线网卡，请自行将 Kernel -> Add 中网卡相关 kexts 的 Enabled 项启用，并删除 boot-args 中相应启动参数的 # 号。此外，还需在 kext 设置中屏蔽 NullEthernet.kext 并在 SSDT 设置中屏蔽 SSDT-RMNE。
```
大佬是不是我更换了无线网卡，所以需要这些操作，但是其中，我第一步就卡住了，我在config.plist中找到了Add节点，但是“网卡相关kexts”指的是哪些我不敢确定，因为里面有好多子节点，除了看到眼熟的“IntelBluetoothFirmware”可能是网卡相关，但是我又看到Enabled已经是true的了；所以当我更换网卡为1820A时，能不能详细点说一下我应该怎么做呢，或者能不能帮我改一改（seepine@163.com），谢谢大佬

**Comment by Pinming** [comment]
> ```
> 本 config 对于无线网卡及蓝牙的默认操作：
> 默认加载 IntelBluetoothFirmware；默认将 Broadcom 无线网卡的各项驱动安置在 \OC\kexts 文件夹中但不启用。
> 如果已经更换了 Broadcom 无线网卡，请自行将 Kernel -> Add 中网卡相关 kexts 的 Enabled 项启用，并删除 boot-args 中相应启动参数的 # 号。此外，还需在 kext 设置中屏蔽 NullEthernet.kext 并在 SSDT 设置中屏蔽 SSDT-RMNE。
> ```
> 
> 大佬是不是我更换了无线网卡，所以需要这些操作，但是其中，我第一步就卡住了，我在config.plist中找到了Add节点，但是“网卡相关kexts”指的是哪些我不敢确定，因为里面有好多子节点，除了看到眼熟的“IntelBluetoothFirmware”可能是网卡相关，但是我又看到Enabled已经是true的了；所以当我更换网卡为1820A时，能不能详细点说一下我应该怎么做呢，或者能不能帮我改一改（[seepine@163.com](mailto:seepine@163.com)），谢谢大佬

1) 操作是正确的。
2) 没有影响，1820A 已经有成功案例了，只是我个人还没测试，因此暂时还没详细加内容上去。
3) 这里是我没说明白……是我的锅……Broadcom 网卡 & 蓝牙的相关 kexts 有：`BT4LEContinuityFixup.kext`、`BrcmBluetoothInjector.kext`、`BrcmFirmwareData.kext` 和 `BrcmPatchRAM3.kext`。将这几个启用（`Enabled = True`），同时禁用（`Enabled = False`）`IntelBluetoothFirmware.kext` 和 `IntelBluetoothInjector.kext`，然后再完成上文中的后续操作即可。
关于网卡驱动可以参考这一篇文章（知乎 @kawauso）：https://zhuanlan.zhihu.com/p/117680791

**Comment by seepine** [comment]
我将kexts进行相应开关，然后删除boot-args的#号
```
<key>boot-args</key>
<string>debug=0x100 npci=0x2000 darkwake=1  brcmfx-driver=2 brcmfx-country=#a alcid=77 keepsyms=1 agdpmod=vit9696 -btnforceclick</string>
```
然后删除了NullEthernet
```
			<dict>
				<key>BundlePath</key>
				<string>NullEthernet.kext</string>
				<key>Comment</key>
				<string>Fix En0 For imess and Facetime, please disabled it if you have compatible wifi card</string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/NullEthernet</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
```
以及SSDT中的
```
			<dict>
				<key>Comment</key>
				<string>Fake ethernet card, work with NullEthernet, please disabled it if you have compatible wifi card</string>
				<key>Enabled</key>
				<true/>
				<key>Path</key>
				<string>SSDT-RMNE.aml</string>
			</dict>
```
然后尝试启动，发现还是卡在启动logo这，下面的读条仍然没有出现...

**Comment by Pinming** [comment]
> 我将kexts进行相应开关，然后删除boot-args的#号
> 
> ```
> <key>boot-args</key>
> <string>debug=0x100 npci=0x2000 darkwake=1  brcmfx-driver=2 brcmfx-country=#a alcid=77 keepsyms=1 agdpmod=vit9696 -btnforceclick</string>
> ```
> 
> 然后删除了NullEthernet
> 
> ```
> 			<dict>
> 				<key>BundlePath</key>
> 				<string>NullEthernet.kext</string>
> 				<key>Comment</key>
> 				<string>Fix En0 For imess and Facetime, please disabled it if you have compatible wifi card</string>
> 				<key>Enabled</key>
> 				<true/>
> 				<key>ExecutablePath</key>
> 				<string>Contents/MacOS/NullEthernet</string>
> 				<key>MaxKernel</key>
> 				<string></string>
> 				<key>MinKernel</key>
> 				<string></string>
> 				<key>PlistPath</key>
> 				<string>Contents/Info.plist</string>
> 			</dict>
> ```
> 
> 以及SSDT中的
> 
> ```
> 			<dict>
> 				<key>Comment</key>
> 				<string>Fake ethernet card, work with NullEthernet, please disabled it if you have compatible wifi card</string>
> 				<key>Enabled</key>
> 				<true/>
> 				<key>Path</key>
> 				<string>SSDT-RMNE.aml</string>
> 			</dict>
> ```
> 
> 然后尝试启动，发现还是卡在启动logo这，下面的读条仍然没有出现...

一般而言关于 config 的配置不会影响读不读条啊…… 就算错误一般也是读条读一半卡住
我想可能是不是要排查一下 BIOS 的设置…… 比如选择 AHCI 模式、关闭 Secure Boot、打开 C-states 这三项→_→

**Comment by seepine** [comment]
会不会有可能我使用的是黑果小兵的镜像？我看其他issues有提到黑果的镜像不能识别u盘?

**Comment by Pinming** [comment]
是的，这个问题我也碰到了……我不太建议用他的镜像 233333
















在 2020-03-27 19:42:51，"seepine" <notifications@github.com> 写道：

会不会有可能我使用的是黑果小兵的镜像？我看其他issues有提到黑果的镜像不能识别u盘?

**Comment by seepine** [comment]
最后检查发现没有开启C-states，开启后能进系统了，目前发现一切正常，但是耳机插入后没有声音，也不能麦克风输入

**Comment by Pinming** [comment]
> 最后检查发现没有开启C-states，开启后能进系统了，目前发现一切正常，但是耳机插入后没有声音，执行ComboJack 文件夹中 install.sh脚本后可以听到声音（下的是最新EFI，我看readme说2.18后的不需要，这里不知道为什么我这边需要执行才能听到声音），另外执行后耳机的麦克风输入还是不行

我没说 2.18 以后版本不需要执行呀…… 只是说不会自动弹出那个选择 `耳麦/耳机` 的窗口了，脚本还是**必须**执行的。
耳机麦克风输入貌似就是不行的…… 我这里也不行。据说好像 iPhone 的原配耳机可以，我手头也没有，不太清楚。

**Comment by seepine** [comment]
好吧，那我这边就是正常的了。
另外，耳机麦克风我使用iphone原配耳机测试了，也是不能输入，看来麦克风的输入是个问题。
另外不知道你有没有尝试过使用AppleALC声卡仿冒驱动AppleHDA的方法呢，通过linux寻找出麦克风正确的节点之类的
[https://blog.daliansky.net/Use-AppleALC-sound-card-to-drive-the-correct-posture-of-AppleHDA.html](https://blog.daliansky.net/Use-AppleALC-sound-card-to-drive-the-correct-posture-of-AppleHDA.html)

**Comment by Pinming** [comment]
> 好吧，那我这边就是正常的了。
> 另外，耳机麦克风我使用iphone原配耳机测试了，也是不能输入，看来麦克风的输入是个问题。
> 另外不知道你有没有尝试过使用AppleALC声卡仿冒驱动AppleHDA的方法呢，通过linux寻找出麦克风正确的节点之类的
> https://blog.daliansky.net/Use-AppleALC-sound-card-to-drive-the-correct-posture-of-AppleHDA.html

7590 上这种什么英特尔阵列麦克风确实是无解的…… 听说 Linux 上有人已经驱动了，但是具体啥情况我也不太明白…… 个人应该没有能力把麦克风驱动上了 23333 还是等大神吧

**Comment by Pinming** [comment]
所以朋友 1820 驱动的咋样了…… 体验还行么

**Comment by seepine** [comment]
除了有次重启后，wifi无法使用，切win10和clover也不行，win10下设备管理器能识别到，但是显示设备无法使用（无法确定是OC引导造成的，还是网卡本身的问题），后来多次重启后就可以使用了，就是除了麦克风输入，其他都没问题

**Comment by Pinming** [comment]
好的，感谢反馈了

**Comment by Pinming** [comment]
打扰了……想抓 1080 的朋友来问一下 HDMI 的情况 方便测试一下吗😂

**Comment by seepine** [comment]
> 打扰了……想抓 1080 的朋友来问一下 HDMI 的情况 方便测试一下吗😂

我一直在用HDMI啊，可以使用很正常，不过声音倒是没法测，我的显示屏没有喇叭

**Comment by seepine** [comment]
我通过直连HDMI接口，扩展坞连雷电，HDMI再连扩展坞，都可以

**Comment by Pinming** [comment]
好的 感谢了🤝

**Comment by 0ytian** [comment]
@seepine 老哥的DW1820A网卡要不要屏蔽针脚？

**Comment by seepine** [comment]
> @seepine 老哥的DW1820A网卡要不要屏蔽针脚？

要，我闲鱼买的黑果小兵的卡80左右，他屏蔽了的，我买来直接换上就可以使用

**Comment by 0ytian** [comment]
@seepine 😂有没有遇到过蓝牙无法使用的情况，我多次重启也没啥用

**Comment by seepine** [comment]
> @seepine 😂有没有遇到过蓝牙无法使用的情况，我多次重启也没啥用

我测试了，可以连接手机、连接airport2，但是偶尔会出现信号不稳定的现象，但是不至于不能用
