### ISSUE TITLE
请问bigsur分支的oc是哪个版本号？

### ISSUE THREAD

**Issue by nieaowei** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#88]

**Comment by Chris51498** [comment]
在线等挺急的  机器已经成砖头了

**Comment by Pinming** [comment]
没记错的话应该是 0.63 正式版吧，直接用 repo 里的版本是没问题的

**Comment by Chris51498** [comment]
> 没记错的话应该是 0.63 正式版吧，直接用 repo 里的版本是没问题的

已经正常开机了，我用了大半天，多次开机。以下问题已经解决
1.开机时间过长。
2.开机之后无法挂载EFI（随缘挂载）之前关机再开机会有用。
3.经常无法驱动扬声器，现在已经可以正常驱动。
接下来存在的问题，只能等wifi和蓝牙更新了
