### ISSUE TITLE
虽然很抱歉 或许您有意将opencore升级为0.6.4吗？

### ISSUE THREAD

**Issue by D0hwQ1** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#91]
虽然很抱歉, 或许您有意将opencore升级为0.6.4吗？

**Comment by Pinming** [comment]
`BigSurTest` 分支已经是 0.6.5 版了。这个分支近期会并入 `master`，如果近期内仍不能解决 10.15 的兼容问题，就可能放弃 `master` 对其支持。
因此现有的 `master` 分支原则上不再更新，如有需要可以手动升级。
