### ISSUE TITLE
Boot Screen Blink

### ISSUE THREAD

**Issue by whuosu** [Pinming/Dell-Inspiron-7590-Hackintosh-Opencore#92]
进入系统读条过程中：
第一段读条
->
屏幕亮度突然变化，屏幕中出现3个苹果Logo带有重影（大约持续0.5秒）
->
第二段读条
->
进入登录界面

中间似乎为加载驱动的过程，但是否有方法可以避免这种闪烁

**Comment by Pinming** [comment]
我掌握的情况看，暂时没有什么办法【捂脸】
